### ISSUE TITLE
Updater: "Failed to save the updater URL!" when selecting language

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1015]
Windows 10 Pro 64-bit, comp_hack Peorth 4.2.1 Hotfix 1

Hi. I'm trying to set up the latest version of the updater.

Before launching the program I have done the following:
I copied VersionData.txt, the webaccess files and ImagineUpdate.dat from the version ReIMAGINE is using (I don't know which version this is but it has no Retry button or language selection and it says COMP_hack Updater 1.0 in the title bar just like the newer version) into the folder and renamed comp_updater to ImagineUpdate.

When launching the program a Language Selection dialogue appears. Clicking OK with any of the languages selected deletes ImagineUpdate.dat and shows the following error message:
![Error message: Save Error - Failed to save the updater URL!](https://cdn.discordapp.com/attachments/226112040735866890/598591578399047680/unknown.png)

Subsequent launches of the program without ImagineUpdate.dat result in the error "Download failed: Protocol "" is unknown". When pasting ImagineUpdate.dat back into the folder and running the updater program again it will work as intended. 

If you want to reproduce this issue multiple times you can delete ImagineUpdate.lang which forces the updater to ask which language you wish to use.

**Comment by compomega** [comment]
The updater is trying to copy the ImagineUpdate_en_US.dat file from the translations sub-folder in place of the ImagineUpdate.dat in the root directory. This feature is meant to allow you to set a different update URL for Japanese and English and switch from them in the options dialog. You can then have one download for the updater and switch between the two Languages easier.

It looks like it was left hard coded to English (en_US). I should fix that as well as check for the existence of the file before removing and copying it. I'll try to fix that before the release we are about to do.

In the meantime try copying the ImagineUpdate.dat as specified above and check that is working.

**Comment by compomega** [comment]
Also, I should pull in the version from the project into the updater binary so it doesn't say 1.0 anymore.

**Comment by alkalime** [comment]
Just tested with the files ImagineUpdate_en_US.dat and ImagineUpdate_ja_JP.dat present and the same error message "Failed to save updater URL!" comes up. 
I tested both with and without a pre-existing ImagineUpdate.dat in the folder.
For the record the folder is on my Desktop and permissions aren't a problem.

**Comment by alkalime** [comment]
After placing the en_US and ja_JP dat files in the translations folder (whoops) the updater now starts properly as long as there's an ImagineUpdate.dat file in the folder with the executable. If there's no ImagineUpdate.dat in the folder it'll fail.

**Comment by compomega** [comment]
Good point I should make sure it only tries to remove the existing ImagineUpdate.dat if the file exists.
