### ISSUE TITLE
Feature request: World server cleanup on launch or shutdown

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1021]
Hi, I think it would be handy if the world server performed a cleanup of characters who have had their KillTime expired upon launch or shutdown.
Currently because of #960 we (ReIMAGINE) have our account deletion function work directly in the Lobby database. I had the idea that I would set the KillTime for characters associated with these accounts to the current timestamp +12 hours but then I learned that the KillTime only runs when the account associated with the character logs in after the timestamp passes. Due to this, when somebody deletes their account their characters are left in the database forever which results in lots of orphaned data, including stuff in friends list, clan list, etc.

Maybe this request is too specific to ReIMAGINE, or too dependent on the other issue in some way, or maybe there's an entirely better way to go about it (a lobby API endpoint for running KillTimes instead?), but it would be wonderful for keeping the DB clean either way.

**Comment by HACKfrost** [comment]
Marking KillTime on characters, removing them from the account character list and marking CleanupRequired on the AccountWorldData record will delete all those characters on world startup. I'm adding a lobby setting to kick off this process on world connection for Eihwaz too.
