### ISSUE TITLE
Digitalize causes skills to be unlearned

### ISSUE THREAD

**Issue by TheRealPeep** [comphack/comp_hack#1025]
While digitalizing with a demon that has the same skills as a player and the player has chosen to learn demon's active skill from lvl 10 digi "example: megi 3" the player will unlearn the skills when digi runs out.

**Comment by HACKfrost** [comment]
I'm assuming this resets when you relog?

**Comment by HACKfrost** [comment]
It sounds like you couldn't get this to work anymore and I cannot as well so I'm closing this. We can reopen if you see it again and have more info.
