### ISSUE TITLE
Logging for moderation

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1027]
Here's some things off the top of my head that would be pretty useful to have in the channel or world logs:

- Trade logs
- Some way to identify which chat channel is being used in more depth such as
    - Zone name to help differentiate say/shout chat
    - Clan name in clan chats

**Comment by HACKfrost** [comment]
I'd recommend zone logging for when a player enters/exits a zone so we don't need to put too much more in each message.

**Comment by compomega** [comment]
Is there any other logging you are looking for that is not currently implemented? Can this be closed?

**Comment by alkalime** [comment]
Logging is great now. Thanks.
