### ISSUE TITLE
Counter Skill using wrong affinity?

### ISSUE THREAD

**Issue by Phazonrad** [comphack/comp_hack#1031]
Steps to Reproduce:
1. Use the Tetrakarn skill.
2. Spawn a demon who often uses counter. (I would suggest enemy 1914)
3. Hit the demon while it is countering.

Expected Behavior: The player should take damage, as counter is an almighty skill.

Actual Behavior: The demon counters you and hits your tetrakarn, then the counter damage is reflected onto it.

Additional Commentary: Short video of it happening. https://www.twitch.tv/videos/462611201

**Comment by Fizzlybub** [comment]
Demon counters are Special affinity, player counters are Almighty affinity
