### ISSUE TITLE
Leaving a zone while changing equipment prevents you from changing equipment after zoning in.

### ISSUE THREAD

**Issue by s4trace** [comphack/comp_hack#1035]
**How to reproduce:**
1. Get to an area with a zone exit that can be triggered by walking into it.
2. Start swapping equipment pieces as you approach the zone exit. Needs to be done relatively fast.
3. Zone out while in the middle of swapping equipment pieces.
4. When you zone in you'll be unable to equip or unequip any item from the inventory and you'll get an error in the chat saying "Equipment change cannot be used in the current state.". 
Some of your item slots will show up as empty in your "Status Equipment" screen.

5. You're unable to equip or swap equipment anymore. Some of the gear slots you swapped before the zone transition will be empty in your character screen.

**Expected Behavior:**
You should be able to swap equipment after the zone transition.

The error message that appears in the chat. 
Note that no matter how many times you try to change gear the error message will appear only once.
![eqchangeerror](https://user-images.githubusercontent.com/15641237/62814334-dfceec00-bb18-11e9-81ce-d04f5229875c.png)

The empty equipment slots, note that weapon and head are the last two items I was changing between the zone transition.
![emptyslots](https://user-images.githubusercontent.com/15641237/62814355-042ac880-bb19-11e9-9e4b-9a18a6ad2467.png)

Note - Using an item or a skill with an incantation time will fix the issue and allow you to equip gear, making this bug pretty trivial once you know how to prevent it.

**Comment by HACKfrost** [comment]
I remember something like this from a bit back that affected any active skill and I was unable to find a fix that didn't have a side effect that was much worse. If this happens can you attempt to activate a different skill then cancel it and try the equipment again? If so it's likely the same bug.

**Comment by s4trace** [comment]
I tried it a few more times, I'm able to use any skill that has an inctantation time to cancel the bug however I noticed that using things like the rental High-Grade Emergency Cure and rental Hyper Candy that can be activated while performing a skill do not fix the issue.

I've encountered a similar problem to what you describe with being unable to use skills but I'm having trouble replicating it. The last time it occured I was teleporting out of an on-going Metatron encounter in Abyss Tower with an Ariadne's Thread. After zoning in I was unable to use any skill, the client would show the animation and effects but the incantation would not work, and I could not change equipment. Only way I found to fix it was reloging.

**Comment by xRaydenx** [comment]
Sorry to bother but this happened too back in aeria.. simply pressing cancel, cancels it.. changing equipment is treated like using a skill, so doing that mid zone causes that to happen.. pressing escape cancels the action of changing equipment, allowing you to change it afterward
