### ISSUE TITLE
A registered world will be removed from the list when it disconnects

### ISSUE THREAD

**Issue by compomega** [comphack/comp_hack#104]
1. Connect a world to the lobby
2. Allow it to create the database connection (if it does not already exist)
3. Disconnect the world
4. Connect the client and observe a crash due to the missing world

This does not exhibit the bug if you never connect to world to the lobby and only use the entry in the database.

This could also be a bug with a channel but this scenario was not tested.

**Comment by HACKfrost** [comment]
This seems to have been fixed by doing the Character and World Lists properly
