### ISSUE TITLE
Docks (B11) Multiple spawns in waves

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1054]
In Docks (B11), depending on the amount of people in the zone ( not in the party ), multiple bosses will spawn during the three boss locations
![20190818_2200_11](https://user-images.githubusercontent.com/48490613/63660069-2ebc8880-c78b-11e9-8abf-d0b9f4f30b94.jpg)
so, in this case you get two different spawns on the same wave, because there are two people in the map. Killing the thors was enough to make the end chest appear

Steps to replicate:
1. Make a party of two people or more
2. Create a B11 run and enter with everyone
3. Go to one of the three boss spawn locations and spend any amount of fragments (ID: 12773 i think) to spawn them

**Comment by Fizzlybub** [comment]
Fixed the issue, it will be in the next content release.
