### ISSUE TITLE
Ichigaya B10

### ISSUE THREAD

**Issue by Evilpaperbag** [comphack/comp_hack#1056]
During gold Ichigaya Camp B10 cannot be accessed from B11 or B9. When going down the stairs from B9 to B10 all doors open except door to elevator room. When going up from B11 to B10 the door in the first large room will not open after clearing to access the rest of the floor. When using B10 card to access the floor all doors will open as it should.

**Comment by Fizzlybub** [comment]
That is the correct behavior; that is how it worked on EN, JP, and CN.
