### ISSUE TITLE
Gate of Hell behaves weirdly on Digitalize

### ISSUE THREAD

**Issue by xRaydenx** [comphack/comp_hack#1057]
**Step:**
**1.** Get Digitalize Level 10 for a demon Race, choose Active Skill as Digitalize Assist.
**2.** Contract a demon from said race and get Gate of Hell as one of the skill on said demon.
**3.** Digitalize with said demon.
**4.** Summon 3 enemy Pixie, separated no further than 30 range.
**5.** Use Gate of Hell on one of the Pixie and ensure that the splash hits the other Pixies.
**7.** Repeat step 4-5 as many times as needed, adding 1 more enemy each time

**Expected:**
Splash damage should be lower than initial damage, as it is when used by demon

**Actual Behaviour:**
Splash damage is magnitude stronger than initial damage, and only at a larger enemy group, 1 or 2 will experience splash damage that's lower than initial damage

**Comment by HACKfrost** [comment]
Can you give an example of how much the damage differs in your setup? I'm testing this and seeing normal damage fluctuation. To make sure we're talking about the same thing here: AoE target damage is not reduced based upon the damage dealt to the primary target, the damage is calculated for each target separately and AoE targets are reduced by a percentage, in this instance 20%. If you do not crit with this skill, the normal 80%-99% damage range is applied. This particular skill can easily result in the primary and secondary targets taking the same amount of damage without crits.

**Comment by xRaydenx** [comment]
![fresh char](https://user-images.githubusercontent.com/54516039/65244696-b775dc80-db1d-11e9-9015-d1cd36e017da.png)

That's the damage difference i got.. Went on a fresh char coz i though debug book might've affected it, but still got the same result.. Wore Destruction Avatar Ticket and Symbol of Destruction Set for 40% LB chance, and 3 Overkiller passives on Digied demon for another 60% LB chance

**Comment by HACKfrost** [comment]
Don't over-complicate it. What causes it to start behaving incorrectly? It's not just digitalize but I can't say what does it if you are adding all this extra stuff to your character. Simplify your setup and let me know what is actually causing it.

**Comment by xRaydenx** [comment]
I added those stuffs so i dont have to use Debug book for consistent damage.. I did encounter some other times where the damage becomes normal.. I'll try again later and repost my findings

**Comment by compomega** [comment]
Is this still an issue? Do you have any more information to add?

**Comment by HACKfrost** [comment]
Closing since we're not getting feedback on the issue anymore
