### ISSUE TITLE
Add additional text encoding support for comp_bdpatch

### ISSUE THREAD

**Issue by HACKfrost** [comphack/comp_hack#1058]
We currently support converting to/from cp932 which only works fine for Japanese and English. Recently I tested a manual string built for GBK (Chinese cp936) and found that the client supports it fine. If we were able to either do one off builds for a couple languages or somehow support swapping converting the .bin encoding during the process, we could support many more languages for translation efforts.

Test string is 去調查下是否還能使用 in which "查" is not handled by cp932.

**Comment by compomega** [comment]
With CP932:
![image](https://user-images.githubusercontent.com/17806249/100165543-bc4bc400-2e77-11eb-9234-76dd311fd35e.png)

With CP936:
![image](https://user-images.githubusercontent.com/17806249/100165553-c1107800-2e77-11eb-8627-95ca730f9554.png)

Note that both CP932 and CP936 are double byte character sets (DBCS) and a single byte character set (SBCS) like CP1251 that uses extended ASCII (values > 127) may not work without some additional client patching.
