### ISSUE TITLE
Chapter 1 Act. 6

### ISSUE THREAD

**Issue by Evilpaperbag** [comphack/comp_hack#1066]
Got a report from another player that act. 6 won't complete. Did it on a fresh new character and confirmed this act 6 chapter 1 is not completing. 
Follows is the specific problem:
- after talking to DB yamaguchi and killing 20 azumis and 10 Gyukis. you are supposed to report back to DB Yamaguchi and get a continuation to talk to the innocent
- This process where you talk to DB Yamaguchi to continue the quest is not working

**Comment by HACKfrost** [comment]
Fix posted on support. Will be included in the next zip posting as well.
