### ISSUE TITLE
Suzaku/Zhu-Que Gold - Stuck

### ISSUE THREAD

**Issue by nijuni-kuro** [comphack/comp_hack#1072]
In Zhu-Que/Suzaku Cavern (Gold), after activating the teleporter on the 1st floor and selecting the 4th option/floor, then clearing the area, I got stuck with no way to progress nor backtrack. The door next to the teleporter in that area never opened and going through the teleporter got me inside a room whose only door wouldn't open.
https://i.imgur.com/4NPTik3.jpg
https://i.imgur.com/yQBvjjh.jpg
https://i.imgur.com/qfudYMk.jpg

**Comment by Fizzlybub** [comment]
The fix for this will be in the next content release.
