### ISSUE TITLE
World server's AccountManager failing to remove characters from clans

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1073]
Hi,

Plague (master of DemonCry clan) deleted their alt Stieg. 
The world.log says:
```
[2019/10/08 20:30:24] DEBUG: AccountManager: Deleting character 'Stieg' on account: <account uuid redacted>
[2019/10/08 20:30:24] ERROR: AccountManager: Failed to remove <account uuid redacted> from their clan
```

As a result, the clan is now functionally broken. "clan chat dead, no purple name on members, no members, no master" See the image below:
![clan error](https://cdn.discordapp.com/attachments/294648067163029507/631254843901739088/aaazzzxx.JPG)

I have checked the world database and found the following:
The account Stieg is on has only one character in the Characters field of the `account` table, and that character isn't Stieg.
The character Stieg still exists in the world's `character` table, with an expired KillTime (21 hours ago relative to this message).
Stieg has an entry in the `clanmember` table matching it to the DemonCry clan.
Stieg's entry in `character` has the DemonCry clan UUID in the Clan field.

**Comment by HACKfrost** [comment]
Is the Clan still there? This all sounds like the clan is gone but all the relationships to it aren't.

**Comment by alkalime** [comment]
Yes, the clan still exists in the `clan` table.

**Comment by HACKfrost** [comment]
Does this character happen to have multiple ClanMember records associated to it?

**Comment by alkalime** [comment]
No, just one record in `clanmember`.

**Comment by Beat4** [comment]
I want to add:
- All the members of the clan see the same clan window 
- We are unable to leave the Clan
-Previous Master/Subs are unable to Add people to the clan

**Comment by HACKfrost** [comment]
Next time you restart, set the world DATABASE logging setting to LEVEL_DEBUG to see what its actually querying. I don't see a hole in the logic so I'm thinking something is either not loading properly or something is loading in place of something else. You don't need to leave the server on after it hits server ready, just need those startup messages.

**Comment by alkalime** [comment]
Today I restarted the world server with those settings and there was nothing in the logs about Stieg or failing to remove a character.
@Beat4 has also notified me that the clan is back to working order again. I'll close this for now since it fixed itself. We can re-open this issue if/when it happens again.

**Comment by alkalime** [comment]
Reopening because this has come up again.
