### ISSUE TITLE
Parallel Boss Defeat Bug

### ISSUE THREAD

**Issue by Phazonrad** [comphack/comp_hack#1074]
(On the Re:Imagine server if this matters at all)
At seemingly random times since the latest content release, every single one of my/my demons abilities will just seem to stop working. I can click a skill, click a demon to summon/desummon, anything. It will look like it worked but it does absolutely nothing except let me incant the skill over and over to no effect. I just got a report in that this was happening to another player as well. The only similar thing I seem to get is "it happens after lag" or "it happens after zoning" and I'm having difficulty recreating it. The only way to fix it is to log off.

Sorry for just a blob of ranting instead of a real way to get this to happen, but that's all I got so far. Hopefully I'll have it happen again or get more reports of it soon.

**Comment by HACKfrost** [comment]
The zoning one is already here https://github.com/comphack/comp_hack/issues/1035.
Do you think its unrelated?

**Comment by Phazonrad** [comment]
If it's the same issue, then something to do with Eihwaz has made it significantly worse. Also no easy "fix" for it anymore.

**Comment by HACKfrost** [comment]
The only thing that changed that affects any skill logic apart from ones that are done charging is the logging rework but I don't see how that is related at all. Are you getting this to happen when you are nowhere near changing zones? Is this always happening in cathedral perhaps?

**Comment by Phazonrad** [comment]
Reports are of it mostly happening in rainy days/die is cast instances (It happened to me personally when spamming The Die is Cast ), then one report of it happening in Zhu Que Gold. All runs where you rapidly zone. I'll have to wait for it to happen again/get more report information before I can give you a valid answer on the "nowhere near changing zones" question though.

**Comment by Phazonrad** [comment]
So it's not random in the slightest, did some testing/got some more info and it's only in the Parallel Zones. The instances with fights, the second you deliver the killing blow it teleports you. However if you manage to deliver a killing blow PLUS shoot off an extra attack that manages to connect afterwords you enter the glitched state upon being put into the new zone.

It seemed to work the best for us in the Mot and Baal fights, because of their very high HP players will often spam their most damaging skill at a high rate and trigger the glitch often.

**Comment by HACKfrost** [comment]
Closing because this is the same as issue #1035
