### ISSUE TITLE
Can't remove clan member

### ISSUE THREAD

**Issue by Phazonrad** [comphack/comp_hack#1078]
Hello, I am trying to remove a member of clan and I can't even though I'm the leader.
Using the bottom option, confirming the window and then absolutely nothing happens. It seems to act like I canceled it instead of confirming it. No chat message, and the clan member remains.
I tried relog, tried full check, tried jp version. and this is on reimagine server if that matters.

EDIT: Weird part is it allowed me to kick two members before this happened.

**Comment by HACKfrost** [comment]
Probably going to need logs from this or I won't be able to reproduce it.
