### ISSUE TITLE
Shock status effect

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1080]
I been testing Shock status effect from Soul breaker Reverse set (ID 27057) and Honestier Set (ID 27170) and i think they are not working as they should be. The point of this status effect is stopping the enemy from moving/casting skills (this is working fine i think) and being able to hit him as much as you want stopping the knockback from your hits.

Here is a good example: https://www.youtube.com/watch?v=TUX2br06aoE
in the minute 0:50 you can see how they pushed the Ganesha and inflicted the shock status, after that they are able to hit him alot with him not being pushed at all. That is currently not happening, in the current version the enemies still get pushed even with shock

also while testing with the Soul breaker Reverse ( Im pretty sure that is what they are using in the video) i noticed the duration of the shock status is shorter than the one shown in the ganesha of the video (i may be wrong about this)

Steps To Reproduce
1 - Get one of the sets listed before (SB reverse for shock on knockback / Honestier for shock on skill) 
2 - Inflict the status 
3 - Try to push him by attacking with one hit push skills like the one from Obsidian mask (ID 6652)

**Comment by HACKfrost** [comment]
I have no reason to believe shock is special. Do you think knockback is not possible when a status effect that prevents you from moving is active? Did freeze or burn prevent knockback too? Does it even need to be a status effect or does 0 movement speed do it too?

**Comment by Beat4** [comment]
but this Shock is not like the burn of freeze effects, its the Blue shock status effect, that is how it is called, there is also a shock caused by the electric skills but that is another status effect (This is the one that is similar to burn and freeze) it has nothing to do with this. When Shock is applied he should stay in place yes, letting you hit him many times.

the main problem is not that he gets pushed, its that you cannont keep hitting the enemy constantly because of the delay there is when he gets knocked back.

i dont think 0 movement speed will do because the delay in the attack will still be there

**Comment by HACKfrost** [comment]
We don't change anything until we understand why it is that way. I just used burn and freeze as examples because they also lock your movement in their definition and would be fairly easy to prove locks you in place while theyre active too. If we can't figure out why this specific status is different, even if its text in the description, nothing will be changed as we are solving a symptom and not the problem. Take a look at one of the status effect data dump spreadsheets floating around and try to identify the rule that could pertain to other status effects as well.

**Comment by HACKfrost** [comment]
We don't have a lot of details on the underlying logic behind this but it _appears_ to be based around a status effect being active before the current hit that prevents movement but does not get cancelled by the hit. I'll code it to this logic and if by some miraculous find we realize this is incorrect, I will change it to match. Very few status effects apply to this logic but there are some that are not the blue shock skills that players would have encountered such as absolute zero and the earthquake status from diaspora.
