### ISSUE TITLE
Nakano Ruins (Silver)

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1084]
In this run there are some doors that wont open no matter what:
![first door](https://user-images.githubusercontent.com/48490613/67613108-fa138000-f77f-11e9-8bef-b59882cb0afc.JPG)
You start from the circle marked on the map, in this layout the door marked with an arrow wont open (this door is only locked in this map layout). i tried: 
- Exploring the entire map
- Killing all the enemies
- Different routes

On the second map there is another locked door:
![seconddoor](https://user-images.githubusercontent.com/48490613/67613205-33002480-f781-11e9-8137-a902db9c9641.JPG) 
for this door i tried all of the above, i even tried starting from the four different points on the center and the door is always locked

also on this floor there is a certain spot where enemies keep spawning everytime you walk by
![spawningpoint](https://user-images.githubusercontent.com/48490613/67613231-8d998080-f781-11e9-9862-2393c42a44a8.JPG)

Lastly on the third and final map, there is another door that wont open (marked with a circle), i even tried going from both sides and i was unable to open it
![lastone](https://user-images.githubusercontent.com/48490613/67613305-5081be00-f782-11e9-8ef1-4043556219fe.JPG)
im not sure if this is how it is supposed to be, but if you follow that marked route on the map you wont be able to come back to the start because all the doors will be locked.

Steps to Reproduce:
1. Open the Silver dungeon until you get the correct layout (shown on the first picture)
2. On the first Floor try to clear the upper part of the map and come back to that door (that works on the other layout)
3. On the second floor check the marked spots above
4. On the last floor try to follow the route marked

**Comment by alphalest** [comment]
In regards to #1:  That door only opened when you set off the Kurama Tengu spawn (and other tengu spawns) by not going to the middle of the map and setting off the Bicorns in the beginning.  If you think it opened another way, let me know what you remember, but the recordings show that the treasure door on that path only opens if you get the kurama tengu group spawn and that's defeated.  

#2 and #3 are mistakes to correct, I'll check on those, and the door on #4.

**Comment by Beat4** [comment]
I tried what you said about #1 and yes it worked, it is just really easy to trigger the middle spawns by accident because some demons spawn right on that spot when you enter that room. (I killed them from far away and avoided the middle spot)

**Comment by nijuni-kuro** [comment]
2nd one should be fixed already, it just isn't applied on Re:Imagine yet. It should be fixed with the next hotfix or content release.
https://github.com/comphack/comp_hack/issues/1079
