### ISSUE TITLE
Demon can no longer be fed specific melon it hasn't reached the cap of.

### ISSUE THREAD

**Issue by Klytius** [comphack/comp_hack#1085]
After recently obtaining a DF passive from Nakano Campsite's Parallel boxes, specifically the Fire TA one, I can no longer feed my demon the melon I was feeding just previous to giving it the passive, which were Raptor melons. The demon itself is Law, and level 95, and has not yet reached the cap of 125k points. 
![DF](https://user-images.githubusercontent.com/57026923/67614361-99307b80-f770-11e9-9f0d-132854e23d70.png)

**Comment by HACKfrost** [comment]
The requirements say the demon needs to be bonded and it is not.

**Comment by Klytius** [comment]
Thanks. I'll try again.

**Comment by Klytius** [comment]
Much appreciated.

**Comment by HACKfrost** [comment]
Thanks for reporting to make sure.
