### ISSUE TITLE
Text and graphics had gone out from screen?

### ISSUE THREAD

**Issue by volcani** [comphack/comp_hack#1086]
This is my first issue so if I have something bad please tell me.

While playing in 1920x1080 window, in opening movie, texts and images looks like sticked out.

![in movie](https://user-images.githubusercontent.com/19391883/67637818-a2147f00-f921-11e9-9b46-8087bcfb0efa.jpg)
![in title](https://user-images.githubusercontent.com/19391883/67637819-a771c980-f921-11e9-8282-a89749e3ea07.jpg)

Is there any way to make fit in screen?
I changed my window size to 1280x720, it didn't comes right.

**Comment by compomega** [comment]
No, we can't fix the client. Sorry.
