### ISSUE TITLE
Act 14 BUG - IoC Shikigami Respawn After Boss Dies

### ISSUE THREAD

**Issue by nijuni-kuro** [comphack/comp_hack#1089]
After beating the Act 14 boss (Shiki-Ouji), the Imp of Chaos Shikigami group keeps respawning infinitely. Killing the boss should've deactivated their respawn, along with everyone else's. This was encountered on the Re:Imagine server.
https://i.imgur.com/SJw2xQl.jpg

**Comment by Fizzlybub** [comment]
Those spawns are summoned by the assassins. The spawns and events for this were taken from the CN server, so there is a fairly decent chance that this was a bug on the actual server (it certainly was in the satan instance). Still, I can fix it easily enough.
