### ISSUE TITLE
comp_rehash won't hash ImagineUpdate.dat

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1091]
Ubuntu 18.04.3 LTS x86_64, using the latest comphack available from [launchpad](https://launchpad.net/~compomega/+archive/ubuntu/comphack)

comp_rehash ignores the presence of ImagineUpdate.dat so it never gets an entry in hashlist.dat. Because of this it's impossible to update that file without having end users do it manually.
I suspected in the past that this is the case with a few files but I could never pin down exactly which ones, I'll update the issue in the future if I can figure out others, unless you guys can think of a reason that it would be skipping over this file specifically.

**Comment by compomega** [comment]
"well, yeah"

It ignores the hashlist.dat, hashlist.ver and ImagineUpdate.dat files (and anything ending in .compressed). The first two are generated by the tool so they are ignored. As for ImagineUpdate.dat I don't remember the exact rational. It has been that way since before we made the project public.

Anyway, is it important this file is included? How often are you going to point the updater somewhere else and what happens if a player failed to update before the older update URL goes away?

**Comment by alkalime** [comment]
In this case I had to change the Information URL. I changed it in the dat files in the translation folder but since that file isn't reapplied with each launch even after being downloaded again the end user still has to either manually edit/copy the ImagineUpdate.dat file or delete the .lang file and select the language again.

**Comment by compomega** [comment]
Interesting, so you update the copies for the different languages and then copy the new file for the two different versions to the main ImagineUpdate.dat file. I can update the tool to include the file but you may just want to fix and build the utility as it may be a while until the package gets updated. Another temporary measure you can do is name the file something else, let it add it, then rename it back in the directory as well as the hashlist.dat file. Or, copy the entry from the translation folder.

**Comment by alkalime** [comment]
> so you update the copies for the different languages and then copy the new file for the two different versions to the main ImagineUpdate.dat file.
Yeah, that's right. Right now I'm telling users to run the updater (so they get the latest versions in the translations folder), then delete the .lang file and pick their language again.
I'll give the renaming thing a shot, sounds like a good workaround for now, thanks.
