### ISSUE TITLE
Destiny - Bug in Daily Reward Cycle

### ISSUE THREAD

**Issue by nijuni-kuro** [comphack/comp_hack#1095]
Doing Destiny for 11 days seems to change the daily reward number from 10 to 0 instead of 1, resulting in not getting a daily reward for that day.

Basically, after getting the x24 Voucher reward, doing Destiny the next day will result in getting no daily reward, as the game will think you haven't done the run that day.

**Comment by Fizzlybub** [comment]
The fix for this will be in the next content release
