### ISSUE TITLE
Quest: The One who thirsts

### ISSUE THREAD

**Issue by InitialP** [comphack/comp_hack#1096]
I have noticed that the correct answer in this quest, when Mada asks you, is missing. This is what I've got.
![which one](https://user-images.githubusercontent.com/29098459/68619679-d82a3500-04c3-11ea-921b-d2ef028087b8.PNG)

**Comment by Fizzlybub** [comment]
![20191111_1549_39](https://user-images.githubusercontent.com/26924047/68620283-2840d180-049b-11ea-9329-6d1c90f1b330.jpg)

It is a translation error.
