### ISSUE TITLE
Unsafe null check: Client not logged in sent drop information

### ISSUE THREAD

**Issue by Aileidia** [comphack/comp_hack#1102]
Remote, public, ReIMAGINE, Windows Server 2016 x64
4.5.0 Uruz running Cerberus_Uruz_Server_Files_11-25 datastore with a few fixes

See title

Backtrace
> [2019/11/25 04:04:25] CRITICAL: Backtrace: comp_channel(objects::ZoneObject::GetDefinition+0x0) c:\users\travis\build\comphack\comp_hack\build\server\channel\objgen\zoneobject.cpp:2962
> comp_channel(channel::ZoneManager::SendLootBoxData+0x84) c:\users\travis\build\comphack\comp_hack\server\channel\src\zonemanager.cpp:2243
>comp_channel(channel::SkillManager::HandleKills+0x256c) c:\users\travis\build\comphack\comp_hack\server\channel\src\skillmanager.cpp:6335
comp_channel(channel::SkillManager::ProcessSkillResultFinal+0x3179) c:\users\travis\build\comphack\comp_hack\server\channel\src\skillmanager.cpp:4431
comp_channel(channel::SkillManager::ProcessSkillResult+0x232b) c:\users\travis\build\comphack\comp_hack\server\channel\src\skillmanager.cpp:3221
comp_channel(channel::SkillManager::CompleteSkillExecution+0xe00) c:\users\travis\build\comphack\comp_hack\server\channel\src\skillmanager.cpp:1983
comp_channel(<lambda_3f71facb7770bdbf950d3709063ef86f>::operator()+0xa9) c:\users\travis\build\comphack\comp_hack\server\channel\src\skillmanager.cpp:1828
comp_channel(std::_Func_impl_no_alloc<<lambda_3f71facb7770bdbf950d3709063ef86f>,void,std::shared_ptr<channel::ChannelServer> &,std::shared_ptr<channel::ProcessingSkill> &,std::shared_ptr<channel::SkillExecutionContext> &,unsigned __int64 &>::_Do_call+0xa1) c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\functional:15732480
comp_channel(libcomp::Message::ExecuteImpl<std::shared_ptr<channel::ChannelServer> &,std::shared_ptr<channel::ProcessingSkill> &,std::shared_ptr<channel::SkillExecutionContext> &,unsigned __int64 &>::Run+0x28) c:\users\travis\build\comphack\comp_hack\libcomp\libcomp\src\messageexecute.h:101
comp_channel(libcomp::Worker::HandleMessage+0xb1) c:\users\travis\build\comphack\comp_hack\libcomp\libcomp\src\worker.cpp:121
comp_channel(libcomp::Worker::Run+0x1fd) c:\users\travis\build\comphack\comp_hack\libcomp\libcomp\src\worker.cpp:94
comp_channel(std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_f0923ea92f8b4eee81a34e73b6976b1e>,std::shared_ptr<libcomp::MessageQueue<libcomp::Message::Message *> >,libcomp::String>,std::default_delete<std::tuple<<lambda_f0923ea92f8b4eee81a34e73b6976b1e>,std::shared+0xa4) c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\thr\xthread:230
comp_channel(std::_Pad::_Call_func+0x9) c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\thr\xthread:209
(_o__realloc_base+0x60)
(BaseThreadInitThunk+0x14)
(RtlUserThreadStart+0x21)

**Comment by HACKfrost** [comment]
This is fixed in the last commit
