### ISSUE TITLE
hell biker skill "hell burner" gets disabled on the colo spell round

### ISSUE THREAD

**Issue by Gricros** [comphack/comp_hack#1110]
this skill is spell type and gets disabled on colo spell round http://megaten.sesshou.com/wiki/index.php/Hell_Burner

**Comment by Fizzlybub** [comment]
In the last part of round 5, one of two status effects are selected randomly, and then applied to everyone in the zone; one of these disables magical type skills and the other is "special" skills, I believe.

If the client says that a particular skill should be disabled by this status effect (by showing it as disabled), then that is the correct behavior and not a bug.
