### ISSUE TITLE
Admin announcement in chat box

### ISSUE THREAD

**Issue by Phazonrad** [comphack/comp_hack#1145]
Aeria's GMs had a feature where they could send a message to everyone at once in the chat box, kind of like an @announce Ticker message but in the chat box itself.

Asking for this because temporary ticker messages scroll past and then they're gone. 
Players participating in events often asking "what did that say?" 

(if this is in the wrong section or wrongly formatted or something I apoligize.)

**Comment by HACKfrost** [comment]
We have API calls that let you send ticker message announcements as well as console messages to all players form a specified sender (to simulate the shutdown messages from Kuroe etc). We can modify the @announce gmand to print to the console too using the sender's name if you'd like but you may want to examine those as a low hanging quick thing to implement on the site for GMs. Our documentation on this front could use some work but check out server/lobby/src/ApiHandler.cpp for the list of admin calls that exist already.
