### ISSUE TITLE
Act 19-3 minor bug about a door in ichigaya camp

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1146]
While doing act 19-3, before entering the boss in ichigaya camp (Gold) if you select not to use the "Cracking-AI-PG":
![xcvbnn](https://user-images.githubusercontent.com/48490613/75402751-7069ef80-58e4-11ea-9750-9586dfc03429.JPG) 
and then you select "Do nothing": 
![Capturexcvnn](https://user-images.githubusercontent.com/48490613/75402776-84155600-58e4-11ea-8adf-0cdc93803785.JPG)
"Some kind of terrific power is groaning..." notification appears when you get near the door, but you can no longer interact with the door. there is no way to proceed unless you exit the run and start again.
![19-4 3](https://user-images.githubusercontent.com/48490613/75402674-34368f00-58e4-11ea-92e4-fc77fda5d234.jpg)

**Steps to Reproduce:**
1-Start Act 19-3
2-Speak with your Alignment's leader for the "Cracking-AI-PG"
3-Start Old Ichigaya Camp (Gold) run
4-Choose the options shown before at the door before boss room

**Comment by Fizzlybub** [comment]
I have this fixed locally
