### ISSUE TITLE
Shinjuku Docks: Deep Levels B14

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1148]
When you try to Re do the Shinjuku Docks: Deep Levels run after the law act 7 is finished, the doors marked in this picture with a X wont open even after killing the enemies, the only ones that open are the ones marked with a O 
![B14](https://user-images.githubusercontent.com/48490613/75404351-0738ab00-58e9-11ea-8fb6-f2f7baa70dc3.jpg)
This is the floor B14, B13 is working fine

**Steps to Reproduce:**
1-Complete Law act 7
2-Start a run of Shinjuku Docks: Deep Levels
3-Clear floor B13 and head into B14

**Small note:** i have not tested this myself since unlocking this act takes a while but i got comments from people about the problem

**Comment by Fizzlybub** [comment]
Fixed by the last content release
