### ISSUE TITLE
Issues in Shinagawa Diaspora

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1151]
First issue is that enemies spawn inside the tower G instead of spawning around it. You can still hit them and they will hit you back only if you are close enough since they cannot move.
![bvcbcvbcvbvcmmm](https://user-images.githubusercontent.com/48490613/76170175-31e2f900-615e-11ea-88c8-fb03b14f0aeb.JPG)

Second issue: if you get discconected while the metatron boss is out, when you log back in, you wont be able to cast anything except Curative spells, or things that dont damage enemies. this applies to both the user and the demon. I tried Closing the client and Opening it again, unsummoning my demon and changing my equipment but it didnt work.
![zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzip](https://user-images.githubusercontent.com/48490613/76170214-8d14eb80-615e-11ea-8e57-4b17ff807ed8.JPG)
You can let the time end and still see the boss running around.
![cccvbvccvbcvbcvb](https://user-images.githubusercontent.com/48490613/76170267-188e7c80-615f-11ea-9dcd-efd8fec8f77f.JPG)

Steps to Reproduce:
1. Start Diaspora run
2. Check Pillar G
3. Proceed to clear the run normally until  you spawn metatron
4. Force close the client 
5. Log back in and try to cast skills 
Optional: let the timer run out

**Comment by HACKfrost** [comment]
These are both fixed for next release
