### ISSUE TITLE
Issue with SP.

### ISSUE THREAD

**Issue by Kristo04** [comphack/comp_hack#1163]
Today was the day when the server got updated. After that I lost all of my SP.
Here is what I did before the server update.
1. I redeemed my 100 SR Chips to SP. (I didn't use them at all.)
2. I wandered around Shinagawa trying to recruit Virtue.
3. The server had shut down and was in maintenance mode.
After logging in I was able to recruit Virtue and happily fused Sarasvati. When I get to acquire demon skills menu and chose for example status ailment skill i saw that i had 0 SP. (The SR Chips were from the hide and seek event I had 40 left later and used them to get 2 skills.). Is there a way to restore it or atleast a way to prevent it from happening?

**Comment by Fizzlybub** [comment]
Which demon did you use the SR passes on?

**Comment by Kristo04** [comment]
I used the 40 SR passes on my Sarasvati. I got her The Essence of the Awareness and Erosion Hex.

**Comment by Kristo04** [comment]
And the other 100 SR passes on my Hoky Night Angel.

**Comment by Kristo04** [comment]
Holy Night Angel has the SP. Is there a way to transfer it to my other demon?

**Comment by Kristo04** [comment]
Going to close this issue.
