### ISSUE TITLE
BDPatch - add additional info to error message.

### ISSUE THREAD

**Issue by 2seoTH** [comphack/comp_hack#1164]
When a mistake is made in any xml file, BDPatch only shows "ERROR: Failed to do X" when launched to save problematic file. Would be helpful if it could show the line number it couldn't parse. Something like this:
![image](https://user-images.githubusercontent.com/47526983/76957789-8426d580-6927-11ea-8b51-98208ef8649c.png)

**Comment by compomega** [comment]
In the past the XML library we used did not provide this information. There is now a new version that seems to add this information. I'll have a look at updating the library and adding this feature. Thanks for the issue!
