### ISSUE TITLE
Act 12 red card possablilty

### ISSUE THREAD

**Issue by Rayerra** [comphack/comp_hack#1168]
Hello I'm posting this because there is a possible way to get the red card from act 12 which shouldn't happen. according to both jp wiki and English wiki there is no combinations that can work with red card being the 1st card you get from the NPC

**Comment by Fizzlybub** [comment]
![meh4](https://user-images.githubusercontent.com/26924047/77215285-ac5e3200-6ae9-11ea-809c-5bde76964076.png)

There is no chance of getting a red card from the NPC.
