### ISSUE TITLE
Ban/kick - Reason /unban

### ISSUE THREAD

**Issue by Evilpaperbag** [comphack/comp_hack#1170]
This could be a feature request. under the options to ban/kick GM could give a reason why. When players logged in they can see why were kicked/banned and for how many days.
on the @ban function we could put how many mins/hours/days they will be banned for.

**Comment by HACKfrost** [comment]
We can't display text to someone in game who cannot get in game. Unbanning can also be done from the admin page we have provided and can also be updated via a normal timed database operation if you so choose. Not sure I see the value in a temp ban being coded in.
