### ISSUE TITLE
Nakano Silver spawn to zone entrance bug while summoning demons in New Order server

### ISSUE THREAD

**Issue by InitialP** [comphack/comp_hack#1172]
I have encountered the issue below in New Order server only. I was told that Nakano Underground files weren't touched at all. I tried the same spot in Reimagine server and I didn't encounter this issue. This issue seems to happen only in Nakano Silver in this map layout. I will do testing in Nakano Bronze and Gold to see if I find the same issue.

![IMAGINE-Version-6663-2020-03-27](https://user-images.githubusercontent.com/29098459/77800578-fe193600-706e-11ea-925d-2e8cce915343.gif)

**Comment by Fizzlybub** [comment]
There was a fix posted for this several days ago on the server support channel; it will be in the next content release as well.
