### ISSUE TITLE
Enhancement Class 5 skills

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1182]
The Shield skill effect from enhancement class 5 leaves after one reflect caused by you hitting the enemy that has reflect on that affinity.

Correct behaviour: the shield should last two uses, this means it should stay after one reflect

Steps to Reproduce:
1-Cast either "Divine Barrier" or "Divine Shield" (Enhancement Class 5 skills)
2 A-If you used Divine Barrier spawn this enemy "Pyro Jack" (ID: 567) and hit it with Agi
   B-If you used Divine Shiled spawn this enemy "Ocypete" (ID: 225) and hit it with normal attack

**Comment by Fizzlybub** [comment]
Information for testing the issue:
Divine Shield is skillID 5487, Divine Barrier is skillID 5488, Duality Pulse is skillID 901
Status effects are 101, 102, and 2442/2443, respectively.
