### ISSUE TITLE
Daisoujou Soul Stone effect

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1183]
The Daisoujou Soul Stone effect (50% nerve affinity if you are neutral) ignores the affinity cap you have and gives you the full boost. I was thinking that it may be similar to the cerberus / orthrus combo SS effect, but the JP wiki does not say anything about it, just a normal affinity boost.

Steps to Reproduce:
1- Reach 100% nerve affinity by equipping this ID:35225 , ID: 2809 and ID: 27094
2- Get two of the same talismans and put the Soul stone of Daisoujou in one
3- Try your damage using erosion hex with one of the talismans, then the other on the same enemy.

**Comment by Fizzlybub** [comment]
There was no issue with Daisoujou soulstone or that necklace; I tried both of them locally with additional nerve boosts and I hit the affinity cap properly.

Using a fresh character:
Equip any talisman.
@enchant 12 0 145 (Daisoujou soulstone)
@item 35225 or @item 35226 (Alice necklace)
@tokusei 20055 1 (50% nerve boost)
Having all three of these active gave me the same result with a nerve skill as having any two of them active.
