### ISSUE TITLE
CharacterList packet Login/Logout Discrepancy 

### ISSUE THREAD

**Issue by onelordkepthorse** [comphack/comp_hack#1190]
https://github.com/comphack/comp_hack/blob/432bbe7cb1f7737735b1610bd4503f847201fcff/server/lobby/src/packets/game/CharacterList.cpp#L131

Currently the Character List reply from the server lists the time as a Login as opposed to a Logout. However, when logging into the lobby, time is listed as Last Logout. 
<img width="188" alt="Screen Shot 2020-04-24 at 7 08 42 PM" src="https://user-images.githubusercontent.com/10914325/80263578-0c9f4100-865f-11ea-8dae-c900662c387d.png">

**Comment by compomega** [comment]
As far as I know the lobby actually records the last logout so the question is should we refactor the code to be consistent with this terminology.
