### ISSUE TITLE
Bazaar moderation

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1205]
It would help to have the ability to force a bazaar to close.

**Comment by HACKfrost** [comment]
Thinking about this a bit. At the bare minimum we should modify the code to close out all bazaars/culture machines from a banned account. I don't think there should be a lesser "no bazaar" ban and you can always unban them after doing it if you want. I can look into the possibility to force closing a bazaar via scripts but it feels a bit hopeless to solve things that way.

**Comment by alkalime** [comment]
>modify the code to close out all bazaars/culture machines from a banned account

I like the sound of this
