### ISSUE TITLE
Additional Sqrat binding for negotiation damage

### ISSUE THREAD

**Issue by Fizzlybub** [comphack/comp_hack#1239]
It would be helpful to be able to safely modify the successAffability, failureAffability, successFear, and failureFear fields within a skill script in the same way as Modifier1 and Modifier2.

**Comment by HACKfrost** [comment]
Weigh how this works in with the suggestion in #1189 plz

**Comment by Fizzlybub** [comment]
Having the same type of binding for the negotiation damage types would work as a stopgap until #1189 is implemented. After that is finished, having the binding available would still remain a useful shortcut.
