### ISSUE TITLE
Failed to trade Prince Spirtits

### ISSUE THREAD

**Issue by Rayerra** [comphack/comp_hack#1240]
when you try to trade prince spirits from mound of Masakado you get this error

![image](https://user-images.githubusercontent.com/17806249/89833023-8e877d00-db1d-11ea-8664-8223dca7f8d9.png)

**Comment by compomega** [comment]
Could you please provide more details. See the pinned issue.

Is this one person or everyone on the server? How repeatable is it?

**Comment by Rayerra** [comment]
everyone on the Rekuiemu server is having this issue since the wyrd release according to some players i talked to

**Comment by Rayerra** [comment]
Update: The culprit is the 2015 summer partial files when removing these files and rebooting the services
The barter exchange for Mound of Masakado's displays and works properly
https://media.discordapp.net/attachments/519243815039795203/758129519101083648/ImagineClientOrig_2020-09-22_19-55-22-802.png?width=1182&height=665

**Comment by Fizzlybub** [comment]
Closing this; it is a result of changes to the NPC Barter file.
