### ISSUE TITLE
Transfer Skills

### ISSUE THREAD

**Issue by Gricros** [comphack/comp_hack#1247]
you seem to be able to call your demon next to you using fusion skills but the demons do not use the skills is only a recall 
i believe jap server we were forced to use skill when you use it, but right now you can use fusion skill to the void for a recall tool

**Comment by Fizzlybub** [comment]
I can confirm that fusion skills that require a target should auto-cancel (without warping the player's demon) after skill 5700 activates if no target is selected.

**Comment by Gricros** [comment]
if is heal or boost does demon warp and use skill or only warp ?

**Comment by Fizzlybub** [comment]
Non-targeted fusion skills such as healing and support should always warp the demon and use the skill.
