### ISSUE TITLE
fixed cooldown skills allowed to stacks

### ISSUE THREAD

**Issue by Gricros** [comphack/comp_hack#1282]
fixed cooldown skills can have stacks atm
that was not possible to do on the japanese server

**Comment by compomega** [comment]
Which specific skills are not behaving correctly? How are they behaving now and how should they be behaving if corrected?

**Comment by Fizzlybub** [comment]
The adjustRestrictions field contains a flag value that determines whether certain parts of a skill have fixed values. Currently, the flag values are 1 (Cooldown time), 2 (Stack count), and 4 (Incantation time). A skill that has all three of these fixed has a value of 7.
Masakado's 奥義一閃 has an adjustRestrictions value of 4, so only Incantation time is fixed.

**Comment by Gricros** [comment]
Mystery Flash

**Comment by Gricros** [comment]
so can you use 4 masa skills in a row or wait for inca

**Comment by TallgeeseHeaven** [comment]
Since the flag is not set on Occult Flash, Consecutive Uses of Skills bonuses do indeed apply, so you may use it multiple times in a row.
