### ISSUE TITLE
Demon friendship should be different based on recruitment method.

### ISSUE THREAD

**Issue by Phazonrad** [comphack/comp_hack#1292]
Right now every method of contracting demons is starting the demon off at the lowest possible friendship "wishes death".
Demon friendship should be higher depending on the method you contracted the demon.

For example aphrodisiac should start the demon at "contracted".
Threatening or hitting the demon should leave them at "used like a slave"
Or if you used a "liked" action on the demon always, it should be "contracted" (example, talk on a pixie)

BTW, I may be getting some of this wrong but if you have any data on this at all it'll be more right than I am. I'm just posting this because I noticed it's been incorrect this entire time.

**Comment by Fizzlybub** [comment]
In our recordings, the friendship value varied from 1200~ to 2500. We saw different values with the same skill being used, damage did not make any (notable) difference and neither did alignment. Like much of the negotiation system, the answer seems to be disappointing in that it is just a random value generated when the demon joins. Currently the range of values we plan to use is 1000 to 2500, giving you a very small chance of receiving a demon at "Looking to Betray".
