### ISSUE TITLE
No Enemy Respawns in UB/UA/Destiny.

### ISSUE THREAD

**Issue by M3t4tr0nx1** [comphack/comp_hack#1323]
Enemies in Destiny respawn until you spawn Mitama wave and kill them, after that only Special Demons spawn at 3 and 1 minute mark and nothing else respawns.

Enemies in Ultimate Battle/Ultimate Attack do not spawn at all after entering the run.
Timer runs out for first round (In UB Treasure Chests spawn at 30 sec mark) and fail screen is shown without getting any BP or Coins due no enemies killed.
However Spectators of Ultimate Battle will still receive the UA Pass from watching.

![UA Fail Round 1](https://user-images.githubusercontent.com/74670381/102616961-b379a580-4138-11eb-895c-940737d6e99e.png)

**Comment by M3t4tr0nx1** [comment]
![Destiny No Spawn](https://user-images.githubusercontent.com/74670381/102625423-c47ce380-4145-11eb-82dd-186176930632.PNG)

![image](https://user-images.githubusercontent.com/74670381/102625516-e4140c00-4145-11eb-8d7c-1d7a1d8b42d1.png)

Destiny Steps:
1.Start the run.
2.Kill 2 waves of each group of demons to spawn Mitamas.
3.Mitamas Spawn 
4.After killing Mitamas no normal enemies respawn (only special demons spawn)

UB/UA Steps:
1. Join Battle and 5 min Count down timer starts.
2. Round starts and there is no enemy spawn.
3. Wait out to round end
4. UB/UA show round end screen with 0 UBP and 0 Coins earned.

**Comment by Fizzlybub** [comment]
Fixed by the latest content definitions.
