### ISSUE TITLE
Taroted items benefit Soul Stone Set Bonus

### ISSUE THREAD

**Issue by M3t4tr0nx1** [comphack/comp_hack#1326]
Encountered a strange issue where Set Bonus of the Soul Stones work with Tarots.

Steps to reproduce.
1.Tarot a Soul Stone that has a Set bonus when paired with other Soul Stones.
2.Repeat above until all SS of a Set bonus are taroted
3.Equip the items with Taroted Equipment
4.Receive a SS Set bonus

![image](https://user-images.githubusercontent.com/74670381/103170238-2672d280-4843-11eb-81d5-c2e13d69c4b5.png)

https://user-images.githubusercontent.com/74670381/103170337-bfa1e900-4843-11eb-815b-3d0e713e9302.mp4

**Comment by M3t4tr0nx1** [comment]
![image](https://user-images.githubusercontent.com/74670381/103170406-3a6b0400-4844-11eb-9eb9-e1ebd225cbf7.png)

Encountered in both versions

**Comment by TallgeeseHeaven** [comment]
Thank you for your report. The problem code has been located.
