### ISSUE TITLE
Updater: "noWebAuth" nonfunctional in comp_client.xml

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1338]
Hello,
Recently we (ReIMAGINE, using comp_updater v4.12.2 (Wyrd)) have had many reports of users getting to the title screen and being greeted with "login server under maintenance". The fix for this is to tell users to open the launcher, click settings, click Patches, click "I want to break my client" then click "Disable Web Authentication".
It seems like noWebAuth is being ignored unless it is in comp_client-user.xml.
I don't really want to have to distribute a comp_client-user.xml as that would kind of defeat the point of that file being separate in the first place.

**Comment by TallgeeseHeaven** [comment]
The description of this issue is incorrect. noWebAuth functions in comp_client.xml, confirmed by testing.

**Comment by alkalime** [comment]
It works for me on Linux using Wine, I don't have more information I can give because this is the issue and steps to resolve it as I have been made aware of it. There is definitely something functioning incorrectly either with the patch itself or the way the config files are read somewhere along the line.

**Comment by compomega** [comment]
This is the issue I am seeing:
1. Player has no `comp_client-user.xml` file.
2. Player opens the settings and clicks `OK` (no changes).
3. New `comp_client-user.xml` file is created by the updater as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <patch name="noWebAuth">skip</patch>
    <patch name="customPackets">apply</patch>
    <patch name="updaterCheck">apply</patch>
</config>
```

This is incorrect as it reflects the DLL defaults and not what is being set as "default" by the `comp_client.xml` file. Note that the `noWebAuth` will break the ability to login but the other patches being applied are also undesirable. What should be created is the following:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<config/>
```

Which changes no DLL settings (assuming the player did not edit the list of client patches in this scenario). You can confirm the patches loaded match the list without a `comp_client-user.xml` by checking the list at the top of the `comp_client.log` file.

@alkalime If this is the issue you see I will merge in a bug fix to correct this. Once the updater is updated the easiest way to correct this is to delete the `comp_client-user.xml` with the undesired overrides and let it re-create if the player goes in and changes settings.

**Comment by alkalime** [comment]
Yes, that sounds like it's the issue.
