### ISSUE TITLE
Gomory Cowrie Exchange not functional, returns an error message.

### ISSUE THREAD

**Issue by s4trace** [comphack/comp_hack#1340]
The Kauri exchange with Gomory in Shinjuku seems to be throwing an error whenever you try to purchase something. I've seen people having issues with it since the newest server version so it might be worth looking into.

![20210112_1505_34](https://user-images.githubusercontent.com/15641237/104403997-6edc0100-5562-11eb-90cd-d2f4234ddd24.jpg)

**Comment by Fizzlybub** [comment]
I can confirm that this only occurs on barter entries that use Cowrie.

**Comment by TallgeeseHeaven** [comment]
Turns out that, in the case of Barter, Cowries are considered BETHEL subtype 0.
