### ISSUE TITLE
Channel Server crashes if a shop's Product ID is higher than 65535

### ISSUE THREAD

**Issue by s4trace** [comphack/comp_hack#1347]
It seems like the channel server will crash if you set a shop's product ID to be higher than 65535. The client has no issue running if you add an entry with an ID above 65535 in ShopProductData. Reading through the ShopProductDataFormat  file, it states that all variables in ShopProductData.sbin are u32. Could it be the case that the server is expecting a u16 for a shop's products when the variable is a u32 in the client's data?

The following error occurs when using a ProductID of 65536 and trying to start the channel server:

> [2021/01/17 21:47:50] ERROR: Failed to load member 'ProductID' for object 'ServerShopProduct' at line 11
> [2021/01/17 21:47:50] ERROR: Failed to load member 'MerchantDescription' for object 'ServerShopProduct' at line 11
> [2021/01/17 21:47:50] ERROR: Failed to load member 'BasePrice' for object 'ServerShopProduct' at line 11
> [2021/01/17 21:47:50] ERROR: Failed to load member 'MoonRestrict' for object 'ServerShopProduct' at line 11
> [2021/01/17 21:47:50] ERROR: Failed to load member 'FilterGroups' for object 'ServerShopProduct' at line 11
> [2021/01/17 21:47:50] ERROR: Failed to load member 'TrendDisabled' for object 'ServerShopProduct' at line 11
> [2021/01/17 21:47:50] ERROR: Failed to load member 'Products' for object 'ServerShopTab' at line 7
> [2021/01/17 21:47:50] ERROR: Failed to load member 'Conditions' for object 'ServerShopTab' at line 7
> [2021/01/17 21:47:50] ERROR: Failed to load member 'Tabs' for object 'ServerShop' at line 2
> [2021/01/17 21:47:50] ERROR: ServerDataManager: Failed to load XML file: /shops/shop-097.xml
> [2021/01/17 21:47:50] CRITICAL: The server could not be initialized.

**Comment by compomega** [comment]
Thanks for the report. While the ShopProductData file in the client has a 32-bit ID, the ID in the server data XML file only supports 16-bit values. This is because the network packet being sent to the client is 16-bit. That's why you're getting the load errors - the XML is not valid. You can't have a shop product ID above 65535.
