### ISSUE TITLE
Current version of nifcrypt does not seem to work.

### ISSUE THREAD

**Issue by s4trace** [comphack/comp_hack#1349]
I've been trying to decrypt the nif files for the maps using the current version of nifcrypt and the result is always "ERROR: File is not encrypted!" even though the file is in fact encrypted and cannot be opened with NifSkope. I've asked around and managed to find a working version of nifcrypt, however I'm not sure which version it is exactly as I only have an executable to go from.

![image](https://user-images.githubusercontent.com/15641237/105176758-55bcec80-5b2e-11eb-9d8c-4549038f9f33.png)

I opened the resulting file from the older version of nifcrypt with NifSkope and seems to be properly decrypted. 
![image](https://user-images.githubusercontent.com/15641237/105177086-d8de4280-5b2e-11eb-8ace-a4374dc76473.png)

**Comment by compomega** [comment]
`comp_nifcrypt`, like `comp_encrypt` and `comp_decrypt`, does not include the original encryption keys used by the client for [the following reason](https://github.com/comphack/comp_hack/blob/6303ecf684a813c93a0d32a6c084145ed075ec51/tools/nifcrypt/src/nifcrypt.cpp#L36). We won't be updating the code and so you would need to build it yourself with the different keys. That being said, the tool is unlikely to have changed from the working build you appear to have.
