### ISSUE TITLE
Armor Modification slot effects are not functional.

### ISSUE THREAD

**Issue by 2seoTH** [comphack/comp_hack#1359]
1)Add "05 00 0F 00 37 00 0F 00 35 00" as ModSlots to any Top item through DB.
2)Equip item on character.

Expected: All the effects apply.
Observed: None of effects apply.

Alternative:
1)Create event with condition bool_tokusei 363416(subID 15 for slot 0 in ModificationExtEffectData)
2)Add "05 00 0F 00 37 00 0F 00 35 00" as ModSlots to any Top item through DB.
3)Equip item on character.
4)Run @event

Expected: Event pass condition check
Observed: Event doesn't pass condition check 

OS: Ubuntu 16.04 x64.
Build: Wyrd 4.12.2 (last commit 0cddcdd)
Content matches git version for 3rd of February.
Unedited 1.666 BinaryData used.

Performed on real machine, also reproduces on virtual machine and public server(New Order).
Linux on each.

**Comment by Fizzlybub** [comment]
@item 6157
@item 42031
Equip an unmodified top. (Duplicate 6157 if using a male character)
@slotadd 3
Unequip top.
Modify the top.
