### ISSUE TITLE
Adding support for custom status effect logic via FunctionID

### ISSUE THREAD

**Issue by s4trace** [comphack/comp_hack#1409]
There exists a field for function IDs in the binary data for status effects. Apparently it has some uses such as demon fusion and cameos statuses, however I'd like to request additional support for writing our own status behavior via Function ID similar to how we can script our own skill behavior with Squirrel scripts. I'm not aware if such a thing is even possible to implement but if it was, it would greatly increase our ability to create custom content.

**Comment by Fizzlybub** [comment]
The majority of functionIDs for status effects have been subsumed by sstatus or constants. The few that have not were replicated in different ways and can be applied in more places. Even if it was possible to implement it, the only potential use that I can think of is firing an event on status expiration, and that is already handled by the existing ON_TOKUSEI_EXPIRED trigger.

**Comment by s4trace** [comment]
The only issue I can see with relying ON_TOKUSEI_EXPIRED is the need for setting up a global zone trigger to get reliable behavior, but I understand this is big feature request for something relatively inconsequential.

**Comment by Fizzlybub** [comment]
Status FID scripts would function identically to a global zone trigger in the server code; each time a status was applied or expired, the server would check for the functionID being set, then search for the relevant script/event.

For now, I am going to close this issue; if either of us (or anyone else) thinks of an application for status FID scripts that is not already covered by tokusei and constants, it can be reopened.
