### ISSUE TITLE
Watermelon Weapons for 2015 Beach Event Not Working As Intended

### ISSUE THREAD

**Issue by Merik2013** [comphack/comp_hack#1414]
I'm being told over and over again that you have to crit for this to function, but not only is that not how this worked when the 2014 Mara beach event was run last year on Reimagine I will briefly outline how this is a logically inconsistent point.

![20210622_1523_54](https://user-images.githubusercontent.com/8151085/123012187-d5760e00-d38f-11eb-8c33-2ff74235df73.jpg)

First We show how the blue melons added for the 2015 event have the protection effect that the other melons have by shooting them with a gun.

![20210620_1158_20](https://user-images.githubusercontent.com/8151085/123012304-022a2580-d390-11eb-8214-fe982114cd24.jpg)

Now we show that the watermelon spear only does 1 damage without critting against a normal watermelon.

![20210622_1524_00](https://user-images.githubusercontent.com/8151085/123012367-1ec65d80-d390-11eb-9d2c-99a3e58aadcf.jpg)

Lastly, we show that against blue melons, and ONLY blue melons, the spear does the appropriate amount of damage WITHOUT critting. The damage you're seeing here is what I saw last year doing the 2014 Mara version of the event. Yes, without critting. I didn't have better gear than what I have now back then either. Why is it that despite the blue melons having the same protection buff that the other melons have, and despite the language on the spear's effects being no different for the blue melon section as it is for the other melon types listed, only the blue melons are treated this way?

My running theory is that something to do with the current version of the event changed something about the melons and now the IDs targeted by the weapon's effect doesn't match the melon's ids. The blue melons wouldn't be affected due to them being added by the event (their first appearance) alongside the spear. That is to say, that since they aren't a carryover the error that may have changed the ID or variable or whatever is going on here hasn't hit them.

**Comment by Fizzlybub** [comment]
Only the blue watermelons lack skill 21017, which reduces damage to 1. Additionally, the tokusei used for the weapons and melon ring do not change when you activate the different summer events.

https://www.nicovideo.jp/watch/sm27065023

This person uses a fusion skill at the end of the video and only deals 1 non-critical damage while the 2015 watermelon weapon is equipped.
