### ISSUE TITLE
Attempting to delete character results in infinite hang

### ISSUE THREAD

**Issue by Aileidia** [comphack/comp_hack#146]
# Steps to Reproduce
With only 1 character
1. System->Select character
2. Immediately try to delete your character

# Expected Behavior

Character should be flagged for deletion

# Actual Behavior

Infinite hang

**Comment by HACKfrost** [comment]
This was occurring due to multiple logins from the same machine.  This is currently not supported.  Issue #191 was created for this bug more specifically.
