### ISSUE TITLE
Digitalizing an already learned skill will disable it once digitalization is over.

### ISSUE THREAD

**Issue by XIXChloe** [comphack/comp_hack#1465]
Steps:
-Learn a skill
-Teach skill to a demon
-Digitalize
-Stop digitalize or let it time out
-Skill is now disabled
-Upon checking the skill is unlearned in expertise menu, and while the point is refunded you can't learn it back.
Logging out and back in solves it, but it's the only known way.

**Comment by compomega** [comment]
Initial fix wasn't correct.
