### ISSUE TITLE
More function to contract CMD

### ISSUE THREAD

**Issue by Rekuiemu** [comphack/comp_hack#1474]
Im making a new request to further the @contract cmd
Like holding demon events where you ca npay out a demon without usng a web api to do it for you.
Adding a function to add a cmd @contract DEMONID IGN
this will give the demon id you list to the person you state. but if there comp is full if like a error be placed where saying the users comp is full. this will best for demon payout events that doesn't need a higher up to execute.

**Comment by TallgeeseHeaven** [comment]
We would prefer that you make a Summon Program item instead.
