### ISSUE TITLE
Wrong message on compshop

### ISSUE THREAD

**Issue by masada-tea** [comphack/comp_hack#1479]
As users buy a thing in compshop, logout message pop on screen.
(It could be only happen in JP client, I haven't try other one.)

**Comment by TallgeeseHeaven** [comment]
I am sorry, there is not enough information here.

For example, what server build? What item? Do you have a copy of the relevant item's ItemData and ShopProducts entries?

**Comment by compomega** [comment]
We need more information to reproduce and look into the problem. If you have more information to add, feel free to re-open the issue and provide it.
