### ISSUE TITLE
C4U not auto casting when low on HP

### ISSUE THREAD

**Issue by Froggowoggo** [comphack/comp_hack#1482]
In game bug, New Order server, Most recent translation patch ( i think at least), 4.12.2 WYRD

Notes: all skill options were enabled , demon has only C4U and samarecarm as recovery spells , samarecarm works and c4u wont. Demon in question is Black Maria

Replication: Teach any demon C4U-> lose Health using any method (i did it by spamming LOA, going to 30% should be fine)

Expected behavior: C4U casted by the demon like all other recovery skills

What happens : C4U is not casted

Comparing with mediaharan (only recovery spells in this scenario are mediaharan and samerecarm) :

same steps as above

Expected behavior : Mediaharan is casted

What happens : Mediaharan is casted

Another thing to note is that, even when the demon gets to low health, it wont heal itself. And both spells in question are categorized as recovery.

**Comment by Fizzlybub** [comment]
Unfortunately this seems to be a flaw of the client's partner AI; some other recovery skills do not function correctly either.
