### ISSUE TITLE
Split Logging

### ISSUE THREAD

**Issue by Rekuiemu** [comphack/comp_hack#1512]
Rename it for a turn you feel is better. Il expalin it here.
Basicly a redesign how the logigng system works
Add the ability to set to either spit your logs the server makes by date/sze or time.
Why you ask have you tried opening and searching a Channel.log thats over 6GB in Notepas++ and watch it lock up for a bit for a simply seach of your log history. 

Log compression and auto archiving will be nice to.
Label this as a feature request since it is one.

The attachment is a example on one of my other hosted servers logging system is set.
you can follow this idea.
![bandicam 2022-02-08 18-39-03-683](https://user-images.githubusercontent.com/43973580/153094103-78a31098-9dc2-4ec6-90fc-ac2394c14640.png)

**Comment by alkalime** [comment]
[LogRotation](https://comp-hack.readthedocs.io/en/latest/chapters/config.html#logrotation) changes the log file out every day and [LogCompression](https://comp-hack.readthedocs.io/en/latest/chapters/config.html#logcompression) compresses the rotated logs.

**Comment by Rekuiemu** [comment]
> [LogRotation](https://comp-hack.readthedocs.io/en/latest/chapters/config.html#logrotation) changes the log file out every day and [LogCompression](https://comp-hack.readthedocs.io/en/latest/chapters/config.html#logcompression) compresses the rotated logs.

TY for your info granted iv omitted this for some time and nice to see you still stalk this place even though you are sus of everything and wear a aluminium hat on your head
