### ISSUE TITLE
Web calling on in game.

### ISSUE THREAD

**Issue by Rekuiemu** [comphack/comp_hack#1516]
Have optional setting to do web calls in game to direct to other web browsers other then IE using comp_client.dll
Why IE to Edges settings don't work on imagine using windows 11 and my flash patch still works on FF and Google Chrome. browsers for flash games.

**Comment by compomega** [comment]
I can add it to the comp_client tracker but it would take significant modification. It's unlikely to happen anytime soon (if ever).
