### ISSUE TITLE
Cathedral of Content not generating valid navpoints?

### ISSUE THREAD

**Issue by your-fantasy-penguin** [comphack/comp_hack#1520]
There seems to be something wrong with the Cathedral of Content's navpoint generation.
At first I assumed this was an issue with my custom QMPs, but loading a vanilla QMP in Cathedral of Content and resetting nav points will break click to move map movement in game.
I've tested and found this to be true for both Home 3 (MT01_001_01) and Shinjuku Babel (MT01_002_01).

**Comment by your-fantasy-penguin** [comment]
I've been told that this issue report constitutes "base disrespect", so I would like to offer a full and frank apology to all offended parties.
Nevertheless, it does seem to me as though the Cathedral does not generate nav points correctly, even with vanilla, unmodified QMP files. 
If that's not the case, it would be greatly appreciated if anyone could explain what exactly I'm doing wrong.

Thanks, with apologies again.

**Comment by compomega** [comment]
You don't have to apologize for anything. People have their opinions and talk amongst themselves on platforms of their choosing. I just ask that if posting on GitHub, maintain professionalism and stick to the issue at hand. Your issue is being looked at and we will get back to you as soon as we can.

**Comment by TallgeeseHeaven** [comment]
Fixed in development branch.

**Comment by your-fantasy-penguin** [comment]
Thank you for looking into this issue and fixing it. Do you have an ETA for when it will be available to use?
