### ISSUE TITLE
Invalid SID authentication error from web auth to lobby

### ISSUE THREAD

**Issue by HACKfrost** [comphack/comp_hack#174]
## Steps to Reproduce
1. Log in with valid account credentials

## Expected Behavior
The lobby connection is successful

## Actual Behavior
The error "User '[username]' session ID provided by the client was not valid: [SID]" prints in the console and the client connection is closed.

This appears to happen off and on on some machines and not at all on others.

**Comment by compomega** [comment]
This is most likely a race condition with the web login giving the client the SID and the lobby login sequence.

**Comment by HACKfrost** [comment]
I'm not so sure this is the case because we saw this during a testing session as well when logging off from the channel using the in game log off functionality.  This causes the user to get "stuck" in a logged in state despite not hitting the UpdateSessionID that is supposed to remove the timeout during logout which would free it up again.  The session ID being checked does not appear invalid as it is 303 bytes with the first 2 being the string size, the last being a null terminator and the string itself not containing another null terminator like I expected it might have.  The plot thickens!
![eyj1cmwioijodhrwczovl3b1ds5zac92n2xyqi83y2e4mtkzmzg5lnbuzyj9 xqgeri2428yqgubqi-qgwicr3vs](https://cloud.githubusercontent.com/assets/22385997/24592348/74f6e4d6-17c9-11e7-81af-3372906a8a68.png)
