### ISSUE TITLE
Equipped head item does not unequip properly when placed in depository.

### ISSUE THREAD

**Issue by NOVAreyner** [comphack/comp_hack#261]
# Steps to Reproduce

Equip any head item, and place it into your item depository.

# Expected Behavior

Head equip is unequipped and placed into depository.

# Actual Behavior

Item itself gets placed into depository but stays visually equipped on character, with the head slot in character status window empty.
Also grants the stats from head piece, taking head piece back out of depository will show it already equipped the moment it goes into the character inventory.
Affects characters and gears of both genders, persists through relogging.

**Comment by NOVAreyner** [comment]
Deleting the item also causes this bug apparently, happens on both genders.

**Comment by NightingaIe** [comment]
After deleting a head item that is equipped and going into character selection your character will be  permanently deleted.

**Comment by NOVAreyner** [comment]
If you glitch a head item by deleting it and then equip another head piece the character is not corrupted when going to character selection screen, so deleting an equipped head item does not cause irreversible corruption.
