### ISSUE TITLE
Skill cancelling doesn't work when booting up servers

### ISSUE THREAD

**Issue by InitialP** [comphack/comp_hack#267]
The test was done in a Local Server. At first, I started all 3 servers. Logged in the client and started it up. I used skills, like Attack, Spin, Counter, Block, Agi, Talk, Threaten, etc. They charged up as expected, however I wasn't able to cancel them with the esc button. I restarted the servers and got the same results.
 
I used a "return to character selection screen" option in the game client menu, re-logged in with the same character and it was functioning normally. Same for restarting the client without restarting the server.

**Comment by HACKfrost** [comment]
Apparently this was an intermittent issue on the original servers for some people. I have not been able to get it to happen anymore so either it is a sporadic client bug or it has been fixed as we added more setup packets being sent. I'll keep an eye out for it and re-open this bug if it occurs again.
