### ISSUE TITLE
Characters are able to send party/friendship requests to themselves

### ISSUE THREAD

**Issue by Fizzlybub** [comphack/comp_hack#271]
Steps to reproduce:

1. Send a friendship or party request to yourself, like a loon.

Expected behavior:
The request is automatically cancelled.

Observed behavior:
The request remains active until it is manually canceled.

**Comment by HACKfrost** [comment]
Strangely enough, this is actually not a bug, at least not a server bug. The client does not send a packet if you type the character's name into the manual request dialogue box and but it _thinks_ it sent it requiring you to manually cancel it.  I don't think this warrants a client change, its just a weird quirk of the client.
