### ISSUE TITLE
Movement speed of skills affecting movement speed of characters

### ISSUE THREAD

**Issue by ApexPie** [comphack/comp_hack#298]
The movement speed of some skills seem to change the ones of characters. The character initiating a skill seems to clear the effect until the skill is used again, although in one of my test overall character movement was bogged down to twitching/rotating, and required a relog.
 Tested skills that affected speeds were (note that the skills were used by a contracted demon) コロナカノン (160), ブリザードカノン (161),  ライトニングカノン (162), ハリケーンカノン (163), and たたり 生唾(910), which all caused the character to slow down immensely.
[Demonstration
](https://drive.google.com/file/d/0ByZlwo_p3WOgTmdVdm9HVEI3Vm8/view)

**Comment by Vooky** [comment]
This happened to me as well, even though I wasn't using any skills (it was Satan).
I created 2 satan, added every skill that has サタン in it's name, tested some of them and suddendly our walk speed was lower than usual, with no fight engaged
