### ISSUE TITLE
Multi-use skills don't stop movement after first execution.

### ISSUE THREAD

**Issue by ApexPie** [comphack/comp_hack#310]
Some skills that are supposed to make the user stay in place during activation don't do so under some circumstance. Skills affected seem to be ones with multiple-use activation.
The user stays in place before the first execution, but is able to move around with the skill activated after that. 
[Test](https://drive.google.com/uc?id=0ByZlwo_p3WOgQ1lYclNMWjJGdms)
Since only skills with multiple activations seem to be affected, I was only able to get this to happen with 
ラピッド skills.

**Comment by HACKfrost** [comment]
You can no longer move after the first shot but if your first skill used on login is a rapid you can pivot around kind of weird. This goes away when using any skill past the first. I think fixing skill timing issues may address this problem so I'm closing this out in favor of the overall skill improvements needed.
