### ISSUE TITLE
Skill incantation interruption

### ISSUE THREAD

**Issue by ApexPie** [comphack/comp_hack#311]
Skills' activations are cancelled by damage when their incantation is finished, but if damage is received while the skill is activating (usually around halfway) it's allowed to finish its incantation. 
[Test](https://drive.google.com/uc?id=0ByZlwo_p3WOgNTQyVG5YOV9xOGs)

**Comment by HACKfrost** [comment]
Closing this specific issue as skill timing is known as a part of the code that needs rework and will need to wait
