### ISSUE TITLE
Summoning a demon higher than your level

### ISSUE THREAD

**Issue by NightingaIe** [comphack/comp_hack#319]
Normally, you can't summon a demon that exceeds your level as seen here:
![20170928_1257_19](https://user-images.githubusercontent.com/30394419/30965255-a5d6b166-a44c-11e7-9cfa-113a892c6990.jpg)

However if you summon a demon within your reach, let's say Injured Kerberos (Wounded Cerberus) which is within your level range, you're able to summon a demon higher level than yours.

![20170928_1304_27](https://user-images.githubusercontent.com/30394419/30965510-93204bb2-a44d-11e7-802e-353fceef8bda.jpg)

**Comment by HACKfrost** [comment]
This is based up leveling your demon past your current level and is fixed by re-logging. Looking into how to communicate to the client to refresh its COMP info as the mag cost updates but not this.

**Comment by HACKfrost** [comment]
This seems to be fixed now. No clue what fixed it exactly.
