### ISSUE TITLE
Cant compile under Ubuntu 16.04.3LTS

### ISSUE THREAD

**Issue by Kobatz** [comphack/comp_hack#328]
Running the latest packages. gcc is 5.4.0. Builds up to 49% then halts everytime. 
I compile on my work lapytop so have to use my work phone to show the error. 
Couldnt cout a log, so my image is my log.

Mint compiling seems to be fine, just not Ubuntu. Makes me wonder if clients on Ubuntu will have issues.

https://i.imgur.com/zySGH77.jpg

**Comment by compomega** [comment]
Add -DNO_WARNINGS=ON to your cmake command (assuming you made a build subdirectory and the source is the parent directory):
`cmake -DNO_WARNINGS=ON ..`

**Comment by compomega** [comment]
Also,
https://launchpad.net/~compomega/+archive/ubuntu/comphack

**Comment by compomega** [comment]
Debian package has systemd init scripts. This should start all 3:
`sudo systemctl start comp_channel`

Place server files in /var/lib/comp_hack and edit the config in /etc/comp_hack

There is 4 packages for the main server, utils, GUI utils, and docs:
comphack, comphack-tools, comphack-tools-qt, comphack-doc

**Comment by Kobatz** [comment]
Was able to use that package to get it to work. Thanks for the help @compomega!
