### ISSUE TITLE
Server execution spawns too many threads

### ISSUE THREAD

**Issue by HACKfrost** [comphack/comp_hack#332]
comp_lobby sits idle at over 60 threads and comp_world and comp_channel reach 10+ with only one connection.

**Comment by compomega** [comment]
The 60 threads on the lobby are mainly a thread pool for the web server. This is normal. I have observed 10 threads on the connection, not more. One of those threads is destroyed and then created again which we can fix; however, you shouldn't see more than 10 at a time. If you do, please re-open the bug.
