### ISSUE TITLE
Sending a TELL to an offline character causes a world/channel crash.

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#337]
Sending any tell to a registered character who is offline causes the world and channel to crash without printing anything useful to the logs. Sending a tell message to a character that doesn't exist doesn't cause a crash.
Fizzy verified for me that this issue exists on a local server too and not just on Re:IMAGINE.

**Comment by HACKfrost** [comment]
I looked into this a bit. The World server caching needs to be revised (specifically for Character) since a fix done to properly clean up ObjectReference instances was done during Pixie. This in theory can blow up during Tell, Clan listing and Clan joining.
