### ISSUE TITLE
Servers crash when too many enemies and actions occur.

### ISSUE THREAD

**Issue by TheFollow** [comphack/comp_hack#369]
While this seems obvious and was also addressed previously, it still seems to be an issue. This can be seen in a few different zones while testing but the easiest to have it occur is zone 1160101 The Obscure Space. It may take a GM napalm to actually cause the crash.

While less prone it may still occur in zone 900201 and other more crowded areas.

**Comment by HACKfrost** [comment]
This is based upon the skill report packet being too large from there being an excessive amount of targets and is a known issue that was not fixed for Pixie as it requires a bit of a restructure of the skill reporting code. The sweet spot seems to be somewhere near 100 targets with no status effects or additional stuff happening and is not likely to occur for non-GM players once spawns are cleaned up.

I'll address this in Kodama.
