### ISSUE TITLE
Tokusei leftovers

### ISSUE THREAD

**Issue by HACKfrost** [comphack/comp_hack#427]
Similar to #364 , creating a placeholder for leftover tokusei changes as this change itself is much too large for one issue.  Remaining functionality to implement (some are already stubbed out) includes:

- Aspects
1. BETHEL_RATE
2. SKILL_TARGET_OUTCOME
3. STATUS_NULL
4. AFFINITY_CAP_MAX
5. CLENCH_CHANCE
6. KNOCKBACK_RECOVERY

As well as tokusei in the file with a "todo" in them.

**Comment by Fizzlybub** [comment]
Type 57, Level based correct table boost (ex. Skill 828)

**Comment by Fizzlybub** [comment]
Types 11/12, Skill HP/MP cost reduction passives are added together rather then multiplied

**Comment by alkalime** [comment]
Rampage passives are not applying stack bonuses to associated skills
