### ISSUE TITLE
Dying in Suginami Tunnels (Grey) locks you out of completing the dungeon

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#440]
If you die in the boss room of Suginami Tunnels (Grey) you'll be unable to re-enter the boss room and therefore unable to complete the instance.

**Comment by nakano15** [comment]
You can craft the plate again, you only need to pass through the steps of making it again:
1-Taking a Level 13 or above demon to the mine and getting the Old World Stone.
2-Taking a Level 13 or above demon to the Cathedral of Shadows of Suginami, and then sacrifice it alongside the old world stone to make a new plate.

You can even do that after completting the main quest, in case you want to capture some demons that spawns on it.
