### ISSUE TITLE
Demon models persist after failed negotiation

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#443]
After failing the negotiation minigame, demon models have a chance to persist in-world and become untargetable.  Other people may not be able to see the failed demons.

**Comment by HACKfrost** [comment]
Waiting for steps to reproduce as I can't get this to happen in the zones I've tried.

**Comment by HACKfrost** [comment]
Confirmed with requester that this has not been seen for a while so assuming its fixed
