### ISSUE TITLE
Client crash on skill inheritance

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#444]
Attempting to move a learned curative type skill from a demon leveling up into the active skill list results in the client crashing, this happened on the Quickly Produced Hathor that's got for free from the H3 Jakyou

I personally wasn't able to replicate this with a spawned in Hathor that was contracted and leveled up with GMands but there's been multiple reports of this happening.

**Comment by alkalime** [comment]
Phazon tested this some more. It happens to her with all status healing skills, curative skills, passive skills, and force skills, all slots. All demons she tested with (Spectre Lv38, Tokisada Lv83).
She noted that it only crashes when placing the new skill into a blank skill slot. Overwriting a skill won't crash the client.

**Comment by alkalime** [comment]
Minor correction, it happened with the force cannon,she tried zandyne and it worked just fine. 

https://cdn.discordapp.com/attachments/364152352942325770/425491669908062212/unknown.png

**Comment by HACKfrost** [comment]
Closing due to it having mysteriously fixed itself
