### ISSUE TITLE
Server accepts new characters with spaces and commas in name

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#489]
Was told this isn't retail behaviour, we have a character called "My name is really long, but why?"
Also can't use GMands on these characters, I don't know if there's an escape character needed for the spaces or something maybe

**Comment by HACKfrost** [comment]
Put user names in double quotes for all targeted gmands. This should work fine.

As for original behavior, we didn't see the need to restrict this.

**Comment by alkalime** [comment]
Fair enough but we also have a character whose name is just a single space and various characters that begin with a space specifically so they can visually have the same name as other characters, is there any chance space can be dis-allowed as the first or last character of a name or something?
