### ISSUE TITLE
[PROPSAL] REST API: admin/get_accounts Allow JSON body to search users.

### ISSUE THREAD

**Issue by Soliel** [comphack/comp_hack#496]
The admin/get_accounts endpoint doesn't provide any functionality for searching accounts, and the admin/get_account endpoint is too strict in that we can only search by username. 

I propose allowing the admin/get_accounts endpoint to take a json body during request, this JSON body should have two or three keys:

- Search Type
  - This key should have a few set values that determine which information to search by. These keys should correspond to the data type
    -"username"
    -"displayname"
    -"uid"
    -"email"

- Search String
  - What to use to search the database with. 

An optional third key that would be useful is the a key to determine strict matching
- Strict
  - A boolean key to determine whether to search for exact matches or not.

So the body would look like
```
{
  "searchtype": "username",
  "strict": true,
  "search": "testaccount123"
}
```

**Comment by compomega** [comment]
This doesn't do anything to address the number of results returned. For example, what if we want it in chunks of 20?

**Comment by Soliel** [comment]
Ahh forgot about that.

In that case we should in pass a few more keys. 

These key can be approached in a few different ways. 

If we return all results and decide to page it via a local cache that refreshes on page load it's not as dynamic but may be easier to approach. This may cause an issue as tables get bigger and responses get too big to handle. 

If we decide to do multiple requests to the server we should define two more keys.

PageSize and PageToken.

PageSize is in the name an integer value for how many results to return. 

PageToken will be an index location on where to continue the search on the second request. 

If a PageToken is passed we should resume the search from there. Either by encoding the query in the token in some way or saving the location server side and having the token be the accessor.

**Comment by HACKfrost** [comment]
Again this can be more easily achieved with a direct DB query. Most read requests will have this answer!
