### ISSUE TITLE
REST API: Add an endpoint to get a characters details.

### ISSUE THREAD

**Issue by Soliel** [comphack/comp_hack#517]
This endpoint should take a username and character name(or just character name if it's unique enough) and return a detailed list of what the characters information is.

the list should include: Name, Level, Skill Info (levels and percents for each skill.), Equipment(Slot and Item ID), and Demons(Levels, skills, rebirth etc).

**Comment by BoreS-ks** [comment]
If possible, I would like to see items in the bag and in deposits.
It is possible only for a certain user level, for example, for 1000.

**Comment by HACKfrost** [comment]
Can just query the DB directly for this and get more info than we could ever provide in a reasonably detailed API call :P
