### ISSUE TITLE
Updater GUI sometimes shows a blank window.

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#565]
For some users of the updater, the GUI only shows a blank white area. Wasn't able to get any more information than a screenshot, it's unknown if the updater continues to function in the background regardless of the UI problem.

Screenshot:
![unknown](https://user-images.githubusercontent.com/17806249/47959404-ee481000-dfa8-11e8-93fd-3ec51cc7a562.png)

**Comment by compomega** [comment]
Can you list which files and folders are included in the updater when running it? For example, is the platforms folder present in the client directory with a qwindows.dll file?

Can you find out what version and localization of Windows they are using?

**Comment by alkalime** [comment]
Had a report just now from Windows 7 32-bit, in Spanish (Spain) localisation.

Files were from the ReIMAGINE launcher (english) zip, which contains the following folders and files:
```
bearer/
- qgenericbearer.dll
- qnativewifibearer.dll
imageformats/
- qdds.dll
- qgif.dll
- qicns.dll
- qico.dll
- qjpeg.dll
- qsvg.dll
- qtga.dll
- qtiff.dll
- qwbmp.dll
- qwebp.dll
platforms/
- qwindows.dll
position/
- qtposition_geoclue.dll
- qtposition_positionpoll.dll
- qtposition_serialnmea.dll
resources/
- icudtl.dat
- qtwebengine_resources.pak
- qtwebengine_resource_100p.pak
- qtwebengine_resource_200p.pak
comp_client.dll
comp_client.xml
debug.log
ImagineUpdate.dat
ImagineUpdate.exe
ImagineUpdate2.dat
Qt5Core.dll
Qt5Gui.dll
Qt5Network.dll
Qt5Positioning.dll
Qt5Qml.dll
Qt5Quick.dll
Qt5QuickWidgets.dll
Qt5SerialPort.dll
Qt5Svg.dll
Qt5WebChannel.dll
Qt5WebEngineCore.dll
Qt5WebEngineWidgets.dll
Qt5Widgets.dll
Qt5Xml.dll
QtWebEngineProcess.exe
VersionData.txt
webaccess.sdat
webaccess.sdat.local
webaccess.sdat.reimagine
```

**Comment by alkalime** [comment]
Hi, quick update with a little more information. Someone else is having this problem (Windows 7 x64 English US, all folders in the right place).

The window shows up with only the window border and transparent contents. Dragging the window away and back onto the screen causes the transparency to turn white. 
Letting the updater idle in this state does nothing, the ImagineUpdate2.dat file doesn't change in size and running ImagineClient.exe doesn't show the reimagine logo upon launch like it would if it had updated successfully from the reimagine launcher. It can be inferred it's not performing a file check or downloading anything in this state.

**Comment by compomega** [comment]
This should be fixed but if this is still an issue please re-open with more information.
