### ISSUE TITLE
Some skill ranges appears to be off, more noticeable for AI and on different servers

### ISSUE THREAD

**Issue by HACKfrost** [comphack/comp_hack#586]
Players have observed shots fizzling, spin AoE hitting inconsistently and rushes being used from further away then they originally were. This seems to affect some servers more than others, possibly some zones more than others too. Some of this may be from hit interrupts but this does not appear to account for everything.

**Comment by blackdragon234** [comment]
To add. AI seems to walk into 'range' no matter what. Most notable is when they use buffing support magic and they'll charge the skill, walk to the player and then cast on self when in a certain range.

Whether the AI casts a spell within range on a player or self should be based on the range of the skill it intends to cast.
