### ISSUE TITLE
Fail to build on Linux

### ISSUE THREAD

**Issue by JiahaoZhan** [comphack/comp_hack#602]
After I followed every step mentioned in README.md, I got the following error message
![screenshot from 2018-12-01 17-39-10](https://user-images.githubusercontent.com/29908925/49333626-0a32d780-f590-11e8-8f38-7bbb3081a5c5.png)
And I checked the folder mentioned it the message. There actually was not a file called sqrat.h.
![screenshot from 2018-12-01 17-40-32](https://user-images.githubusercontent.com/29908925/49333638-40705700-f590-11e8-86fe-026c60e8efa0.png)
How should I solve this issue?
Thanks!

**Comment by compomega** [comment]
```
git submodule update --init --recursive
```
