### ISSUE TITLE
Nakano Stone Site: Silver

### ISSUE THREAD

**Issue by compomega** [comphack/comp_hack#697]

**Comment by InitialP** [comment]
I don't think I've seen anyone report this but when you enter the Silver plate run and try to exit via the teleporter, it doesn't work. Shall I make this a new issue or keep this comment here?

**Comment by Fizzlybub** [comment]
This issue is still open; the dungeon is not ready to be entered yet.

**Comment by InitialP** [comment]
Thanks for clarification. I had a sneaking suspicion that I wasn't meant to enter inside of it.
