### ISSUE TITLE
Yo how do I make the content come from into the cathedral and shit?

### ISSUE THREAD

**Issue by ASTRONAUTPISSSOLUTION** [comphack/comp_hack#860]
Because so far this shit ain't do what it says on the label

**Comment by compomega** [comment]
Please restate your question or problem clearly with less "colorful metaphors".

**Comment by ASTRONAUTPISSSOLUTION** [comment]
aight whatever man you can cathedreal your own content cuz your shit is whack and dont launch app
![low on memory](https://user-images.githubusercontent.com/47183866/51992685-5d98a780-24a5-11e9-9cfd-2ae3de93c3ea.png)

**Comment by compomega** [comment]
This is an issue with your PC, not our software. Please close out of applications consuming memory, upgrade your PC, scan for viruses and/or give up.
