### ISSUE TITLE
-Windows- sqrat.h not found

### ISSUE THREAD

**Issue by Senkay201** [comphack/comp_hack#861]
Hi,
i opened the comp_hack.sln solution file and wanted to build it. But i get around 280 times the same error(i looked in th scr folder and there was only sqratInt64.h in it). Any idea what went wrong?

Fehler	C1083	Datei (Include) kann nicht geöffnet werden: "sqrat.h": No such file or directory	comp	C:Desktop\Neuer Ordner (7)\comp_hack-develop\libcomp\src\ScriptEngine.h	39

**Comment by Senkay201** [comment]
Aftr using git clone the command "git submodule update --init --recursive" worked , thanks for your explanation!

I assume that the pre-built Windows version(.msi) is working fine. I still figure out how to set up and start the server with the linux explanation from "The Definitive Guide" since from the .msi installation the comp_lobby/world/channel are closing right after i clicked on them.
And thanks again for your help with the sqrat-problem !

**Comment by compomega** [comment]
The pre-built Windows version in the msi is built as a service. They are meant to be started and stopped by the Windows Service Manager so that you can log out and leave it running.
