### ISSUE TITLE
Windows Installer - World Server service fails to start if Lobby Server service wasn't installed

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#874]
Steps to reproduce:
    1. Install the hathor-4.0.2 release (this issue occurred on Windows Server 2012 R2) with every option but Lobby Server checked for installation
    2. Attempt to launch World Server from Services.msc

Expected behavior:
The World Server launches

Actual behavior:
The World Server fails to launch with the following error:
`Error 1068: The dependency service or group failed to start.`

This might also be the case if the Channel Server is installed without Lobby/World installed too, but I haven't tested it.

**Comment by compomega** [comment]
#972 fixes this. Note that this will also stop and remove the services when you uninstall. If you install the world and channel the channel will depend on the world but the world will only depend on the network. If you install only the channel the channel will depend on the network. If you install the lobby and channel they both depend on the network (the channel doesn't depend on the lobby).
