### ISSUE TITLE
comp_bdpatch with CSkillData.bin breaks skill effects

### ISSUE THREAD

**Issue by Verreater** [comphack/comp_hack#878]
Simply using the original japanese CSkillData.bin (or the working half translated one) , turning it into an .xml and turning it straight back to a .bin breaks skill visuals.

comp_bdpatch load cskill Cskilldata.bin CSkillData.xml
comp_bdpatch save cskill Cskilldata.xml CSkillData.bin
-> https://gyazo.com/57d78cfeafd652dbf8ff561473b309d9

The CSkillData.bin file also gets reduced from 31,204 KB down to 19,323 KB during that process.

No idea what exactly is happening :^)

**Comment by HACKfrost** [comment]
CSkillData has massively padded strings that still dynamically list their size for whatever reason. When we save it back we don't preserve size-prefixed string padding. Maybe the client is anticipating all strings to be in byte multiples of four but greater than zero? I don't think we've encountered this anywhere else yet.

**Comment by Verreater** [comment]
Quick question on this one.
Does the issue happen during saving or already during loading it?
I'm asking because i'd like to know if i can continue translating that file for now or if i should wait.

**Comment by HACKfrost** [comment]
Saving does not add the padding needed so you can work on it still. If we find its more complicated than that when it's fixed, it wouldnt be a lot of effort to mash the strings from one into the strings from another later
