### ISSUE TITLE
Novice and Artisan Digitalize have the same time duration

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#881]
Just as the title says, Novice and Artisan Digitalize have the same time duration. Artisan should last a few more minutes than Novice digitalize. (i dont remember the exact values)

the Steps would be to simply try turning on a Novice digitalize and then an Artisan digitalize to compare the times

**Comment by HACKfrost** [comment]
Currently it is based off of if you have artisan available or not. It's 3 minutes before you have it and 6 for any demon type once you have it. I'm assuming the issue is that non-mitama is supposed to remain 3 minutes after you get the valuable to artisan?

**Comment by Beat4** [comment]
yes, i think that would be the case, novice should remain with the same time
