### ISSUE TITLE
Issues in Shibuya Quartz (Gold)

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#882]
The first problem is that only the one that created the instance can enter it, when the other party members try to enter the run by touching the pilar at the entrace of quartz, the menu to create runs pops up.

Steps:
1. Having a party of 2 or more
2. One of the two has to create the instance
3. The other party members have to try to enter

The second problem i found is that in a certain room there is a blue crystal with a pixie that keeps warping you into the same room, creating a loop. there is no way to proceed from here
![thisthisthis](https://user-images.githubusercontent.com/48490613/54318553-78daf480-45c5-11e9-818c-dfe8bb3b4b0d.JPG)

Steps:
1. Creating the Quartz Gold instance
2. At the start go to the Southeast room and keep going foward from there (there is only one path you can follow)
3. When you get to the part with two white Crystals on Left and Right with a pixie in the middle, choose Left
4. Then one more room and the next one is the Room with the Loop
5. Talk to the pixie and then touch the Crystal

**Comment by Fizzlybub** [comment]
Fixed in the next content release.

**Comment by InitialP** [comment]
I would like to add more to this and what happens after you cross the blue crystal. I've got equipment that raises all my stats above 100. The Pixie's text confirms that you can enter. I press the crystal and get teleported to the area behind the door next to her. The circled spots in red are shown below in the image. The yellow line is the spot where the door opens once you beat the demons. The door works fine.

![image](https://user-images.githubusercontent.com/29098459/57581545-fed5c780-74b0-11e9-8dbe-944e5e125fc6.png)

The real fun starts when I press the crystal after having warped via the blue crystal. I get teleported to a room with treasure. Please see the map below. I warp to the area circled in red (the one with B). I go down below where the red square marks the treasure after all mobs are killed. The door opens to the crystal underlined in yellow.

![image](https://user-images.githubusercontent.com/29098459/57581611-b9fe6080-74b1-11e9-829d-b7ae3162410a.png)

I press the crystal and receive the following (please see below). This happens in Imagination server so I need verification if Reimagine and Megaten.Ru have the same issue. 

<img width="769" alt="Quartz Gold past blue crystal and past white crystal" src="https://user-images.githubusercontent.com/29098459/57581644-24af9c00-74b2-11e9-9fe0-e98fc35bc995.png">

**Comment by Fizzlybub** [comment]
I see the issue, and I have it fixed locally.

**Comment by Beat4** [comment]
I actually found another path that is not working currently, 
![this is it](https://user-images.githubusercontent.com/48490613/61424459-e6878c00-a8e9-11e9-828f-9823d8ba7a75.JPG) once you get here there is nothing to do, You are Stuck.

Steps to Replicate:
1. Create a Quartz Gold Run
2. Take the Crystal to your Left from the start 
3. Keep advancing floors until you get to the one shown in the picture above
