### ISSUE TITLE
Lucifuge Demon Soul's "+5% LB Chance when using Almighty" seems to be more than 5%

### ISSUE THREAD

**Issue by Verreater** [comphack/comp_hack#887]
I don't know the exact percentage, but it for sure is way higher than 5%.
I put Overkiller 2 & 3 on my demon (20%+30% LB chance) as well as 
the Lucifuge Demon Soul (ID: 38226) in Demon Force.
It is supposed to (according to ingame description and JP Wiki) give: +10% Final Crit, +5% LB chance and +20% LB Power, all for Almighty skills.
This should be 55% LB Chance.
Now this is Cup of Babylon with that setup:
https://gyazo.com/d8d254ab1dcd8cb6b10e93dcbdf9aa62
Non Limit Break hits seem pretty rare.

This is with a Mada Demon Soul(+5% LB Chance for all Skills) instead:
https://gyazo.com/8350bff60b93e638c5e3c5eab318fa29
Critical Hits are way more common

With an additional 10% LB Chance to the first setup, every single hit was a Limit Break, so i am thinking it is actually +40% instead of +5%?

**Comment by Fizzlybub** [comment]
Will be fixed with the next content update.
