### ISSUE TITLE
Attacking during Zone Change breaks Character/Demon until relog/resummon/death

### ISSUE THREAD

**Issue by Verreater** [comphack/comp_hack#889]
https://gyazo.com/5e682ad1325baec47c392b4a9f8c1021
Easiest done with Demon Partners, as you can still move while they attack, but it can also be done with your character or demon during wildcat.
https://gyazo.com/6f3c0ff70f7a2bcb6666f177e825668a

Simply throw an attack at an enemy close to the teleporter and start moving into it as soon as possible. If done correctly, you will not be able to cast any Skills. The Effects will appear, but incantation will not actually start.

**Comment by HACKfrost** [comment]
This will likely not be fixed. It cannot be replicated on CN (which is gone now) and would likely require a complete rewrite of how skill requests are handled. It can be corrected by hitting ESC/trying another skill while selecting the demon or character who was trying to use it.

**Comment by Verreater** [comment]
Oh, i couldn't use any skills at all, and esc didnt fix it, but i just now saw #578
