### ISSUE TITLE
Partner Cooldown Equipment and Epitaph do not function

### ISSUE THREAD

**Issue by ReyoSekihara** [comphack/comp_hack#891]
Any demon used with various equipment and epitaphs that are supposed to reduce incantation and/or cooldown do not receive the cooldown effects. Incantation cutters are working fine, just not the cooldown cutters.

**Comment by HACKfrost** [comment]
Can you provide an example of a skill ID and item ID to test? It helps reproduce the issue faster and helps identify if the skill itself has restrictions such as being unable to reduce cooldown on it.

**Comment by ReyoSekihara** [comment]
I have the issue with all skills; none of them have reduced cooldown. 36386 is the item ID of a epitaph that grants a 60% cooldown cutter. I'm not sure of most of the item ID's for various equipments, though I think 32520 had a cooldown component for partners. None of the cooldown cutters from the partner extra's are working, whereas the incantation cutters are working. One extra has something like 70% reduction to both incantation and cooldown, but only the incantation part is taking effect. I've double checked, and all of the items I've tested specifically point to the partner, not the player, for their cooldown reductions. I hope that isn't too little information to go off of.

**Comment by Verreater** [comment]
With what skill are you trying it? Because they work just fine.
Note that cooldown reductionis capped at 95%.
With both of the example items: https://gyazo.com/9657009d5e1cc923316f9133910e6ab2
Nothing: https://gyazo.com/5d9088177c5647b53935fec80f679648

**Comment by ReyoSekihara** [comment]
There must be a glitch on my server then, because no skill, be it Fairy Ring, Maragidyne, Megidora, Media, or anything else, has a change in cooldown no matter what I do. Character cooldown is working perfectly though, it's just partner's that isn't :/
I am aware of the reduction cap as well.

**Comment by ReyoSekihara** [comment]
I just now logged back in and my cooldown gear and epitaphs are working...I haven't the foggiest idea why it has decided to start working. I can only hope it stays working as I didn't do anything to change it...
