### ISSUE TITLE
Ongyo-Ki Plugin Turn In Broken

### ISSUE THREAD

**Issue by kiliera** [comphack/comp_hack#900]
Having the plugin in your inventory does prompt the text chain to turn in the oni you were supposed to make, but the NPC does not recognize the demon as being correct, even with all necessary skills.

![what in the heck](https://user-images.githubusercontent.com/49291427/55587873-9e9d7a00-56e9-11e9-96ac-73b9d42eb5e5.png)
![what in the heck 2](https://user-images.githubusercontent.com/49291427/55587874-9f361080-56e9-11e9-9be1-2e30b8ad89f8.png)
![what in the heck 3](https://user-images.githubusercontent.com/49291427/55587875-9f361080-56e9-11e9-9d96-38af03b1d77d.png)

**Comment by Fizzlybub** [comment]
Fixed in next content release

**Comment by kiliera** [comment]
YAY!
