### ISSUE TITLE
TMG Building (False)'s south side is not using southern demons

### ISSUE THREAD

**Issue by Verreater** [comphack/comp_hack#905]
The northern side is supposed to null all magic, the southern side all physical.
However, right now, the southern also spawns the Elementals and Mitamas with the titles
北方の精霊 and 北方の御魂, which are the northern versions that null magic, instead of the southern versions that null physical. (南方の精霊 and 南方の御魂)

(IDs for Elemetals: North: 5671-5674, South 5675-5678)
(IDs for Mitamas: North: 5679-5682, South: 5683-5686)

The Ghost enemies seem to be correct.

**Comment by Fizzlybub** [comment]
Fixed in next content release
