### ISSUE TITLE
Mound of Masakado Bug?

### ISSUE THREAD

**Issue by TheRealHitoshura** [comphack/comp_hack#911]
Hi all, It's Hitoshura here.
I got teleported into someone's Destiny when doing opening a Masakado instance. I selected 5 seals. I was the only one that got teleported while the other members of my party were able to do the run.

Much love.
![20190415_1558_23](https://user-images.githubusercontent.com/49658543/56161674-21e78700-5f98-11e9-9b01-abaea4a69f26.jpg)

**Comment by Fizzlybub** [comment]
This was occurring during a period of server instability; please let us know if it happens again when the server is stable.
