### ISSUE TITLE
After last big update Pierce Shot does barely hit 2-3 targets instead of 3-5

### ISSUE THREAD

**Issue by RezDK** [comphack/comp_hack#914]
Expertise Shot Class 7 skill Pierce Shot (sadly the only aoe i have as gunner) barely hits 2 (at best3 if lucky) targets now after ueno mirage patch. Before the update hitting 3 to 5 targets was pretty consistent. As it is now it's not worth using anymore because it takes too much time to re-position yourself everytime just to hit 2 enemys at mid-range.

**Comment by HACKfrost** [comment]
Line AOE was corrected in this release. It was much too large by accident and should match the adjusted area more accurately. If there is reason to believe it is incorrect now independent of what it did before the update, you can reopen this and we can reexamine.
