### ISSUE TITLE
no Attack based skills used by wild demons

### ISSUE THREAD

**Issue by Gricros** [comphack/comp_hack#915]
bosses and normal demon from AI are unable to use any kind of Attack based skills the list includes:  Slash, Slash Combo, Beast Claw, Punch, Tailwhip, Kick Combo, Eight End, Tackle,  Charge  Fierce Fang, Thrust, Gnaw

**Comment by Fizzlybub** [comment]
I idled in Suginami on my local server after taunting some normal enemies, and they used Attack skills.
Same occurred when I attacked Garm in Suginami Tunnels (Bronze).

Can you provide any further clarification?

**Comment by Gricros** [comment]
high lvl boss demons dont use them

**Comment by Fizzlybub** [comment]
Masakado uses his attack skill. There is nothing different about his AI type (2, 1, 1, 1); it is very common among enemies.  

We have a structure in place for overriding the frequency at which specific action types are used, so if you want to build a custom AI type yourself, or conduct a poll among users to reach an agreed upon amount for each action type, that would be fine.
https://github.com/comphack/libcomp/blob/develop/libcomp/schema/ailogic.xml

**Comment by Gricros** [comment]
yeh seems like the stronger the demon skill the less likely to use the actk type 

here we can see masakado using it https://www.youtube.com/watch?v=aFpJqkpzZFg 10.49 he uses it but on the version we got he never does
