### ISSUE TITLE
G1 Timer stays after failure

### ISSUE THREAD

**Issue by Verreater** [comphack/comp_hack#918]
Failing a G1 Trial by exceeding the time limit (16m in quartz silver, 13m in gold being fast ones) makes the timer stay on screen even after leaving the dungeon.
Starting a new G1 Trial doesn't replace the timer until you finish the dungeon, making you unable to see your current run's time.

**Comment by InitialP** [comment]
To add to this, you can make the timer disappear if you select "change characters" and go back to the lobby. Select your character to log back in. The timer display disappears (confirmed in Imagination). This should also work if you close the client and reopen it.
