### ISSUE TITLE
Potentially skill iheritance or a skill issue(hard to classify)

### ISSUE THREAD

**Issue by InitialP** [comphack/comp_hack#925]
I was trying to inherit a demon skill Nervous Edge. It is Nerve affinity based. This is what I found out:
1. If you go to Old Ichigaya Camp Gold and try to inherit from Erosion Hex (also nerve affinity), the bar progress doesn't grow. I left my demon to be hit with those hexes at least 20 times. No noticable change in value.
2. Shibaboo from enemy works but is about 0.5-1 point with a 1.5 multiplier boosting item.
3. Bind Voice from Punks Coward gives ~7 (rarely 8) points when under 1.5 times multiplier (Incenses of Heredity) as well as when under 6 times multiplier (Incense of Memory). No noticable increase from 7 points.
4. The demon in question doesn't reflect Nerve affinity inherently however it has a high resistance against it. (Pallas Athena)

Either it is the skill or the item that doesn't grow/multiply the values properly.

**Comment by InitialP** [comment]
Update: Tested out Inheritance of Mediarahan. Used Incense of Heredity (1.5 multiplier) vs Incense of Memory (6 times multiplier). Results are below:
Base(no incenses used): 13 times healing with rental Bead Chain= 1% increase
Incense of Heredity(1.5x): 12 times healing with rental Bead Chain=1% increase
Incense of Memory(6x): 12 times healing with rental Bead Chain=1% increase

Expected result: Higher multiplier should give 1% increase with way less healing using item like rental Bead Chain:
13 heals=0.13% (base)
5 heals=0.2% (1.5x Heredity item)
2 heals=0.78% (6x Memory item)

**Comment by HACKfrost** [comment]
Oh it seems the correct table entry titled RATE_EXPERTISE (our chosen name) boosts expertise rates when on a player and skill inheritance when on a demon according to status effects that grant it. Currently only the player side is wired up. Haven't tested the base bug at all yet.
