### ISSUE TITLE
TMG BUILDING FALSE Infinite loop boss speech

### ISSUE THREAD

**Issue by BeijiWeng** [comphack/comp_hack#931]
So the boss on tmg is infinitly looping his speech causing on lag on server and when we stayed till the end crashed the whole server

**Comment by Verreater** [comment]
You have to provide more information.
Steps to reproduce the issue and maybe evidence that it truly was this that caused the crash.
If you are unsure, ask in the respective server's help channel.
Because if you mean Re:imagine, the server was restarted manually.
