### ISSUE TITLE
Missing Gakis of Suginami

### ISSUE THREAD

**Issue by nakano15** [comphack/comp_hack#933]
The last time I played on the English Server, there were a group of Gakis that used to spawn in Suginami at night, they spawned around the area where the D of the Subway Dungeon is, in the Minimap.

I believe they spawned in groups of 3, on the ruins at that place. And just like the Onmorakis that spawns south of that place, they also were used for a quest from the Weapon Store vendor in Home 3.

**Comment by Verreater** [comment]
![image](https://user-images.githubusercontent.com/48488511/56862872-c792f100-69af-11e9-9755-998982782d13.png)
They spawn, you were just at the wrong location

**Comment by nakano15** [comment]
Wops, I forgot that they spawned there, too. But they used to spawn on the ruins at the D position on the minimap too.

By the way, thanks for the answer.
