### ISSUE TITLE
lucifuge run no branchs

### ISSUE THREAD

**Issue by Gricros** [comphack/comp_hack#934]
when taking party theres a high chanse theres no branchs from boss boxes
only the box from the middle at left side gives reward

**Comment by Fizzlybub** [comment]
This needs more information; however, if it is the bug that I think it is, it has already been fixed locally.

**Comment by Gricros** [comment]
is only on hard mode normal mode got no bug

**Comment by Gricros** [comment]
ok if you do alot of normals ones also start to bug
