### ISSUE TITLE
Bynary File-Crash of Client-

### ISSUE THREAD

**Issue by Sephiroth90** [comphack/comp_hack#937]
hi, I have a problem with compiling some binaries.
In this case with the CIconData_COMPShopCategory
does not work and is not viewable when I insert the file
CMessageData_Charastic.sbin the game does not hold. Until the previous days the game held the file but now nothing to do. The compilation is correct and it is as from standard but when I arrive to the warehouse or I open the compshop it gives me error of version of the game. How can this inconsistency be solved?

I tried to put another similar file not compiled at the levels I arrived at and it works, I would like to understand where the problem is if possible please
![errore objects](https://user-images.githubusercontent.com/50193143/57066413-667b5e00-6ccc-11e9-847d-530072ef2ffc.JPG)

**Comment by Sephiroth90** [comment]
ah when you complete the binary status, my status is no longer visible but does not affect the client

**Comment by Sephiroth90** [comment]
so i'ts natural close code can't complete file because therre is an eror in close code? i read noww this mistake, so i don't seems many normal i think it's not faul of comp ptch but by original file

**Comment by Sephiroth90** [comment]
I have fiixed file with a cleaner Xml software, but , dbcomp convert has corrupt file code of charystics

**Comment by Sephiroth90** [comment]
File of Status is  perfectly corrected i have controlled it but i can't see my status/any status  into game

**Comment by compomega** [comment]
It sounds like the problems you are having are a direct result of your custom files. That doesn't belong on our issue tracker (see #930). That being said I will try to help you.

First, please note that the comp_bdpatch tool is meant to dump and generate the bin files for the latest Japanese client (1.666 and the one right before it) ***only***. Any other version of the client bin files may still work but are not supported. For example, any bin files from the original English version may have a slightly different format and will probably not dump correctly.

When trying to debug your bin file changes, here is some tips:
1. Try dumping the original Japanese bin file with the tool and make only one change at a time.
2. Try dumping your new bin file and confirming that everything is still there.
3. Ensure that all the original entries have some replacement in your XML before you generate the new bin. If not, the client won't be able to find the text and other information it needs.
4. Make sure you don't change anything except for the text. Changes to the other fields could break the entry.

If you are looking for more help I would need to know:
1. What specifically is incorrect or missing? For example which icon or message isn't showing up.
2. The XML you were using for the relevant icon/message/etc.

**Comment by Sephiroth90** [comment]
So All i't fixed how i explain to Hackfrost only problem in Iconcompshop doesn't appear and sometimes don't convert correct byte on status file. I close issue, because don't need  just please correct problem of byet  and inconCOMP thanks for attention that give me. Like requeste by hackteam i don't need take open this issue i just talking with Hackfrost and he know. Thanks Very much sorry for retard for closing issue was very busy
