### ISSUE TITLE
Surrounding-type spins not connecting with enemies within range if there is one mob among them who nulls/reflects/absorb the affinity

### ISSUE THREAD

**Issue by Vincnette** [comphack/comp_hack#939]
Those spins, if hitting an enemy who nulls/reflects/absorbs its affinity, will not connect to any of the mobs within its range until the mob who negates the damage is taken out. 

The example below is Nyx using Magical Meteor with Scathach (who nulls mystic affinity) within its target area. As illustrated, it doesn't connect to the Pallas Athena and the Dis (who are vulnerable to mystic and also within the range).
![ezgif-1-036cf760d7a9](https://user-images.githubusercontent.com/48882976/57307174-5d332c80-70e4-11e9-9c4b-62caae5896eb.gif)

This is an abnormal behaviour for surrounding type spins, a type of skills that does not require a target selection.

**Comment by HACKfrost** [comment]
That's the primary target in this gif. Can you confirm this doesn't happen when you manually target one that does not null/reflect but includes one that does? Also is there any chance the correct behavior is documented somewhere? As I'm sure you are aware, this is the correct behavior for the primary target of say a projectile that hits in a radius around the primary target.

As with all skill logic we have to identify the rule, not correct the action type. I'm willing to believe a source radius skill does not fizzle for other targets based upon how the primary target handles it but I would like to see something showing this if possible.

**Comment by HACKfrost** [comment]
Alternatively if you can find proof of a spin hitting and being reflected by the primary target as well as other enemies in the radius that would also prove the theory. As it stands, the primary target reflecting the hit would cause the source of the skill to be hit by a single reflected hit. If this were to change and you hit a group of the same demon that reflected the hit, they would ALL reflect it back. This seems like something that would have happened semi-frequently given that behavior and easier to notice than other enemies standing close enough in the radius.

It's also important to note that a source radius AoE without a primary target does exist in things like napalm items which does not have this same behavior. Changing this makes the primary target relatively pointless in the skill's execution if I'm not mistaken unless the skill has AoE damage reduction for additional targets.

**Comment by Fizzlybub** [comment]
https://www.youtube.com/watch?v=HEmoWTmpmxY

Video example of a source radius spin being reflected by multiple targets (10/11 seconds in)

**Comment by Fizzlybub** [comment]
Alpha and I discussed this issue a few weeks ago, and these are the conclusions we were able to reach for some of the AoE types.

Frontal 1: Other enemies are not hit on primary target NRA | only user is hit on reflect
Frontal 2: ? | ?
Frontal 3: Other enemies are not hit on primary target NRA | AoE around user is hit on reflect
Source: Irrelevant
Source Radius: Other enemies are hit on primary target NRA | only user is hit on reflect
Straight Line: ? | ? 
Target Radius: Other enemies are not hit on primary target NRA | AoE around user is hit on reflect
Variant Source Radius: Other enemies are hit on primary target NRA | only user is hit on reflect

**Comment by HikaruM** [comment]
Request for Information: 

Testing with Manual-Target Circular AoEs (ones where you have to click a target before activation):  Do they behave as intended, or does the behavior still surface?

Testing with Manual-Target Linear AoEs (ones where you have to click a target before activation) [ex: Pierce Shot/Outrage Barrett Skill/DD]:  Do they behave as intended, or does the behavior still surface?

Testing with Auto-Target Linear AoEs (If any of these exist), please check behavior as well (I will confess, I don't remember of any off the top of my head)

**Comment by Phazonrad** [comment]
comparison of source-radius spins for JP vs ReIMAGINE with the reflecting enemy being the closest.

JP: https://www.twitch.tv/videos/57729601?t=00h14m22s (Lamia Behind Anzu gets killed.)
ReImagine: https://www.twitch.tv/videos/433761343 (Nozuchi behind Dis does not get killed.)

**Comment by HACKfrost** [comment]
The plot thickens:
1m22s in here this is behaving exactly like our current implmentation: https://www.nicovideo.jp/watch/sm27540171
The Anzu/Lamia thing looks like what you're describing but I can't say for sure if the primary target isn't actually the Lamia there for some weird reason because they're in such a similar spot relative to the player. Where the enemies are relative to eachother doesn't actually matter, its all about the primary target the client chooses.

**Comment by HACKfrost** [comment]
After finding a very unlikely source to put the source radius discussion to bed for good, I decided to fill in the rest of the gaps by checking our packet recordings. The behavior for each is as follows:

Behavior 1: Reflect and null on primary target have no bearing on AoE whatsoever
	SOURCE_RADIUS
	FRONT_1
	FRONT_2
	SOURCE (doesn't actually AoE)
Behavior 2: Null, double reflect, reflect to null and absorb stop all AoE. Otherwise reflect activates AoE on source from target.
	TARGET_RADIUS
	FRONT_3
Behavior 3: AoE does nothing upon initial null or reflect
	STRAIGHT_LINE
	SOURCE_RADIUS2

Counter/dodge stop all AoE as the full effects don't even display when these occur
