### ISSUE TITLE
Quartz Gold

### ISSUE THREAD

**Issue by Sephiroth90** [comphack/comp_hack#944]
I wanted to write about the evolution of the project to enter Quartz Gold as you know, you are the developer engineers who have been trying to solve this problem for some time, there is the impossibility or some error in entering that dungeon.
We have recently learned that some server have found the solution to enter the Dungeon without problems, all fixed. I do not know who the author of this is if you are you or others, we wondered if these could be shared with all server. Thanks For reading me and possibily answer

**Comment by HACKfrost** [comment]
All content files are being shared will all servers. If anything is being modified by the hosts themselves, we do not have access to them.

**Comment by Sephiroth90** [comment]
Thank You Hackfrost
