### ISSUE TITLE
Software  error? Client Crash Binary Corrupted 

### ISSUE THREAD

**Issue by Sephiroth90** [comphack/comp_hack#946]
hi, I have a problem concerning the software, all the files I convert are almost all corrupt, I checked, the code is fine, it is during the conversion that happens the damage of the file. When I convert from .sbin to .xml, the .xml files are practically empty, they have no data messages or text only codes with empty CDATA [       ] ETCs. Now I'm downloading a virgin version to see if it works, if for updates it should work the place as soon as possible, but I lost a lot of time trying to convert sbin xml to sbin but nothing. Is there any solution? Thanks for the attention :)

**Comment by compomega** [comment]
Here is some clarification of how the tools work:
__comp_bdpatch__ - This tool can convert __unencrypted bin__ files into XML and then save XML back into __unencrypted bin__ files. It only supports the file formats of the bin files listed in the help. These bin files must be from the most recent Japanese client version. Any other versions like the North American/English and Chinese bin files are __not__ supported. The files do not contain information about their format so the tool has no idea if the file is right. It will "convert" it anyway; however, the output file will be wrong. Likewise the client may expect an __encrypted sbin__ in the correct format to load properly without crashing. Please ensure you have the right file before running the tool or starting the client.

__comp_encrypt/comp_decrypt__ - These tools encrypt (bin->sbin) and decrypt (sbin->bin) respectively. The encryption key used by our builds has been created specifically by us. It does not work with client files that have not been re-encrypted first. To work with client files that have the original encryption key you would need to modify [Config.cpp](https://github.com/comphack/libcomp/blob/develop/libcomp/src/Config.cpp) and re-build the tool from source or find a build that already works with these files. We won't help you do that so please do not ask. We also do not want want a pull request with the original key so don't create one. If you have the client patch (and the matching re-encrypted files) with the updated key the tools should work fine.

If you are taking an XML and converting it back into an __encrypted sbin__ to place in the _BinaryData\Shield_ directory you need to:
* Run __comp_bdpatch__ to save the XML into an __unencrypted bin__ file.
* Run __comp_encrypt__ to convert the __unencrypted bin__ into an __encrypted sbin__.

**Comment by Sephiroth90** [comment]
I downloaded the virgin Comp_hack software the server doesn't crash anymore and the conversions do it normally. Probably a few bookstores had been corrupted. Now everything is settled. Thanks Very much was very problem. if want can close issue or i can close myself
