### ISSUE TITLE
Quest "The Fountain of Youth" not working as intended

### ISSUE THREAD

**Issue by Vincnette** [comphack/comp_hack#947]
Steps to reproduce:
1. Accepting the quest "The Fountain of Youth" from the Perceptive Woman in Kakyo Castle.
2. Collect all the items required in the quest and activate the Creation expertise.
3. Report to the Perceptive Woman.

Expected behaviour: The woman takes her requested items and increases your Creation expertise to class 1. The quest is completed.

Observed behaviour: She didn't take any item and didn't increase your Creation expertise either (despite the text message saying that your items have been taken and the expertise has been increased). The quest wasn't closed.

**Comment by Fizzlybub** [comment]
It will be fixed in the next content release. If you want to complete it right now: one of the items being removed is a single digit off; bring a normal Cabinet as well as a Cabinet Pro and it will work.
