### ISSUE TITLE
Defensive skills should interact with Negotiation skills

### ISSUE THREAD

**Issue by Fizzlybub** [comphack/comp_hack#948]
Steps to Reproduce:
1. Approach a negotiable enemy that is using a defensive skill.
2. Use any of the negotiation skills on the enemy.

Expected Behavior:

Talk: The demon's active dodge skills activates on any Talk skills, causing it to give a negative conversation response.
Threaten: The demon active guard/counter skills activate on any Threaten skills, causing it to give a negative conversation response.
Taunt: The demon active guard/counter skills activate on any Taunt skills, causing it to give a negative conversation response.

Observed Behavior:

The demon's defensive skill is not activated by any negotiation skills, negotiation proceeds as normal.

**Comment by HACKfrost** [comment]
The last time I looked (and just confirmed again) fc2 has information about talk and dodge and threaten and guard but nothing for taunt or counter. Do we have a source on those at all?

**Comment by HACKfrost** [comment]
Confirmed in packet recordings that talk can be dodged, threaten can be countered but guard is guard broken, taunt can be guarded but counter is guard broken. Everything else appears to just stay active as if nothing hit the defending demon.
