### ISSUE TITLE
Biology not working properly while digitalized

### ISSUE THREAD

**Issue by Eucliwood1** [comphack/comp_hack#949]
I know Biology should boost your stats based on your base stat.
But, if you digitalize, you get more.
![Sin título](https://user-images.githubusercontent.com/50780249/57973965-1d433380-7987-11e9-8d5a-56a8e425ef56.png)
as you can see in the image, left one is without Ability Strengthening: Magic, then i used it and my stats got increased by 89 instead of 24.

**Comment by HACKfrost** [comment]
Do we have any reason to believe this is incorrect from the original servers? I was under the impression that the strength of digitalize was when it applied the stats which right now is before boosts are applied. If that were not the case the demon stats would just be a flat add at the end.

**Comment by Eucliwood1** [comment]
i dont know if you understan me. Just in case:
In both cases i am digitalized.
On the left image i am not using Ability Strengthening: Magic
On the left i am using it. thats the only thing it changed.
the problem i noticed is that im getting 89 magic from it. When it only should be 24.
Since its on the white base 99, and that doesnt change between both images.
Unless you are telling me that the digitalize stats boost is added to the base, instead of been added at the end.

**Comment by HACKfrost** [comment]
Yes that is what I am telling you for how it works now. The strength of digitalize how it was described to me and talked out on the wiki is that it is added to your base stats but it does not change them visibly (the white text) from our recordings. If you have reason to believe this is wrong we can re-examine when they actually apply.

**Comment by Eucliwood1** [comment]
Sorry then. I'll close this

**Comment by HACKfrost** [comment]
It's nothing to apologize for, I'll be the first to admit I could be wrong about something like this but yeah that's how/why it works the way it does now.
