### ISSUE TITLE
Enemy skills that are Dodged/Countered/Nulled/Reflected do not raise skill inheritance

### ISSUE THREAD

**Issue by Fizzlybub** [comphack/comp_hack#950]
Steps to reproduce:
1. contract 1872 for a Hua Po
2. contract 568 for a Pixie
3. Fuse Pixie and Hua Po to make Garm.
4. Summon Garm, and use tokusei 421504 1 demon to apply 100% magic reflection to him.
5. enemy 1519 to spawn an enemy with fire skills.
6. Have Garm attack the Pyro Jack until the enemy uses a fire skill.

Expected Behavior:
The Garm should reflect the fire skill, and the inheritance meter on Agi should increase.

Observed Behavior:
The Garm reflects the fire skill, the inheritance meter on Agi remains the same.

Notes:
All sources state that skills that are nulled/reflected should still increase the inheritance meter; I am uncertain whether dodged/countered skills should increase the meter.

**Comment by HACKfrost** [comment]
Can confirm from recordings and wikiwiki that the target automatically avoiding the hit does not raise inheritance for the source but manually avoiding (dodge/counter) does. Additionally the source manually avoiding the hit does not raise inheritance but automatically avoiding does.
