### ISSUE TITLE
API: Allow users to delete their own accounts

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#960]
Users should be able to delete their own accounts, [currently the only way for an account to be deleted via the API is by an authenticated admin user](https://github.com/comphack/phpapi/blob/develop/src/API.php#L407) (unless I've missed a trick somewhere).

**Comment by HACKfrost** [comment]
This call would need to be updated quite a lot as right now it doesn't check the current state of the account, nor does it clean up anything associated to the account. That being said, I think modifying it so regular users could use it would be useful.

**Comment by HACKfrost** [comment]
This works with the new suggested service account design much like password reset would. Nothing custom needed anymore.
