### ISSUE TITLE
Wrong soulstone award for Mirage's "Tears of Brass" quest

### ISSUE THREAD

**Issue by Vincnette** [comphack/comp_hack#961]
Steps to reproduce:

1. Accept the quest "Tears of Brass" from Gaian Priest: Lu Shu in Ueno Mirage entrance hall (x23, y21) on a Thursday (JST).

2. Open a silver level Mirage, clear all fly rooms and finish the dungeon.

3. Report to Lu Shu for rewards until he gives out a soulstone.

Expectation: The soulstone he gives should be SS: Scorpio (魂合石・天蠍)
Observed behaviour: What he gives is SS:The Scales (魂合石・天秤) instead.

**Comment by Vincnette** [comment]
Side note is that he gives the correct runestones on Thrusday (Runes of change - Fehu) but the wrong SS.
I'll need to more to verify whether there is also a mistake in the reward pool in the rest of the week.

**Comment by Fizzlybub** [comment]
I fixed the issue on my local, the fix will be in the next content release.
