### ISSUE TITLE
Wrong rune rewards for Ice Cave excavation on Sunday

### ISSUE THREAD

**Issue by Vincnette** [comphack/comp_hack#962]
Steps to reproduce:

1. Open and finish an Ice Cave run on a Sunday, JST time.
2. Dig for random awards from the light on the wall until a runestone (of any size) or a relic is obtained.

Expectation: The received runes/relics should be one intended for Uruz rebirth (runestone of Courage/Egg of Pangu) 
Observed behaviour: Ingwaz rebirth items (runestone of Harvest/Ark of the Law), whose drop schedule is on Saturday, are obtained instead.

**Comment by Fizzlybub** [comment]
![meh4](https://user-images.githubusercontent.com/26924047/58763199-dd06b800-8525-11e9-85f7-3064ffd5c921.PNG)

D104_10401XX_MINE_04_RELIC_B is sunday, D104_10401XX_MINE_04_RELIC_A is default (making it saturday)

There is one minute each day where you would receive the wrong rewards, and that would occur only if the value 2400 is not the same as 0000; I am not sure what the issue could be besides that.

**Comment by Vincnette** [comment]
That would be a possibility if I did Ice Cave at the last minute of Sunday, but my latest run was at around 22:00 and it still gave me the wrong runes/relics. /headscratching

**Comment by HACKfrost** [comment]
We confirmed this and fixed with a recent commit so it will be corrected in Eihwaz.
