### ISSUE TITLE
Synthesis Bugs 08/06/19

### ISSUE THREAD

**Issue by SuruReImagine** [comphack/comp_hack#975]
https://streamable.com/y1s65

During synthesising the item, on a failed attempts a completely broken copy of the item will appear in the same spot as the non-synthers inventory. Upon interacting with it it will disappear from the inventory.

Timestamps are:
2:25
5:16
8:13

**Comment by Kitbil** [comment]
https://streamable.com/yy6ac

00:40 failed SS but item not being damaged and can't be repaired. 02:10 log back in and item now damaged and can be repaired. 03:15 second SS failure. 04:00 relog and item has disappeared from inventory.

**Comment by Kitbil** [comment]
I did a bit further testing, it seems that to ghost copy that the synthesizer gets shares it data with the original, as in, if the synthesizer deletes the ghost copy it will also delete the real item. I hope this helps.

**Comment by SuruReImagine** [comment]
We did a bit further testing, it seems that to ghost copy that the synthesizer gets shares it data with the original, as in, if the synthesizer deletes the ghost copy it will also delete the real item. I hope this helps.
