### ISSUE TITLE
Pentalpha entering bug

### ISSUE THREAD

**Issue by Farlan1** [comphack/comp_hack#979]
1. Joining Pentalpha, yellow, Indrajit. 

![image](https://user-images.githubusercontent.com/51677902/59230556-7bf67880-8be6-11e9-9b42-3529a77b2501.png)

2. Clearly saying 'Indrajit'

![image](https://user-images.githubusercontent.com/51677902/59230604-a5170900-8be6-11e9-9176-0f10a0ad96ee.png)

3. Entering.

![image](https://user-images.githubusercontent.com/51677902/59230636-c677f500-8be6-11e9-964c-e519fa59eaf8.png)

4. Instance with Indra.

![image](https://user-images.githubusercontent.com/51677902/59230693-f921ed80-8be6-11e9-9bbf-7dc7a7062d8e.png)

Tried with 2 alts - result is the same, always Indra when picking Indrajit.

**Comment by Farlan1** [comment]
People reporting that Kresnik's instance also leads to Indra, so maybe it's all of them?

**Comment by HACKfrost** [comment]
Yes that is correct. Indra top tier!

...we're looking into the bug right now...
