### ISSUE TITLE
Didn't receive kauri points in Pentalpha after last week's reset

### ISSUE THREAD

**Issue by Farlan1** [comphack/comp_hack#989]
Not sure if it's a bug, but after last week's reset my main character didn't recieve any kauri points (Indrajit instance). He accepted Pentaplha 2 days after it's release, was waiting for it to be fixed.

![image](https://user-images.githubusercontent.com/51677902/59888065-8ecf3100-93ce-11e9-888c-bcdf66251825.png)

My alt who entered in the release day (Indra instance) got 100 points.

![image](https://user-images.githubusercontent.com/51677902/59888178-1f0d7600-93cf-11e9-859d-e748ed6f0f52.png)

Weirdly other alt, with whom I tried if it's fixed (Indrajit instance) also got 100 points. 

![image](https://user-images.githubusercontent.com/51677902/59888125-dce43480-93ce-11e9-9287-b2b4e3234167.png)

Sadly I don't remember how many points were we getting on Japanese server for every place your demon took, looks like in that list Indrajit was 4th last week.

Sorry if it's nothing and thank you.

**Comment by HACKfrost** [comment]
Is this local or on a hosted server like ReImagine? There is currently a memory leak happening on world servers with many players and I believe it will cause this to happen. If you experiencing this on one of these servers we should probably close this issue and retest the fix included in the next release. We can re-open this if it still occurs.

**Comment by HACKfrost** [comment]
Closing due to no response. We can open this again if we think the issue was not actually addressed.
