### ISSUE TITLE
Servant Puppet Upgrade Quest is Bugged

### ISSUE THREAD

**Issue by nijuni-kuro** [comphack/comp_hack#995]
While the quest "Reward for Abundant Food" does upgrade the Servant Puppet to the chosen variant, the items used for upgrade are not taken from the inventory and the quest remains active, never completing. Tested on a local server running Cerberus_Peorth_Server_Files_6-20.
![ImagineClient 2019-06-23 10-51-46-74](https://user-images.githubusercontent.com/52109692/60011263-b4cc2e00-9679-11e9-9133-2f7b0e8a67ee.jpg)

**Comment by Fizzlybub** [comment]
I have this fixed locally
