### ISSUE TITLE
Servant Spirit Alpha Upgrade Retains Non-Upgraded Item

### ISSUE THREAD

**Issue by nijuni-kuro** [comphack/comp_hack#999]
During "Growth of the Vessel Spirit and Bond" quest, beat 10x Pure Fire Flamies, 10x Obsessive Demon God Thor & 10x Guardian of Sin Jikokuten, then talk to St. Germain with all plasma-deconstruction items required for the next stages of the quest and Servant Spirit Alpha in your inventory. Quest will be completed properly, plasma items will be removed and upgraded Spirit Avatar Alpha will be acquired - but the base Spirit Avatar Alpha won't be removed.
![ImagineClient 2019-06-25 22-56-24-22](https://user-images.githubusercontent.com/52109692/60218008-616f0100-986e-11e9-9c4d-867f882a9fc6.jpg)

**Comment by Fizzlybub** [comment]
Fixed this locally.
